### PR TITLE
API change: Removed completions api

### PR DESCRIPTION
**Pull request by hoodmane**
As I suggested in #984, I don't think we should re export the completions API. The exported API is very modestly simpler, has many fewer options than the Jedi API, and is less well documented. We should send users to the Jedi docs and have them use it directly. If we think that Jedi should offer a simpler "very basic API" we should suggest a change to Jedi.

### CODE REVIEW

**Comment by rth** [comment]
I agree, I think the initial motivation was compatibility with iodide, but in practice it's indeed better to use jedi directly.  And if iodide development continues in the future, it could be re-defined as part of a iodide specific plugin, but not great to maintain it in the public API.

It's a breaking change so definitely we need a changelog entry.

@casatir @gzuidhof Please let us if this change would be problematic for you.

**Comment by hoodmane** [comment]
I don't see why Iodide shouldn't define this themselves if they need it. There's no C code present, it doesn't rely on internals, and in fact there's nothing about "get completions from jedi in iodide" that is different from "get completions from jedi in native" (other than all the recursion errors, but the `get_completions` API did nothing to mitigate them).

**Comment by gzuidhof** [comment]
Starboard doesn't make use of it, so no objections from me :). Thanks for asking!

**Comment by casatir** [comment]
This is fine for me. It is not used in Basthon and I plan to use Jedi directly.

**Comment by hoodmane** [comment]
> I plan to use Jedi directly.

Presumably because the reexposed `get_completions` is too weak for most practical purposes.

**Comment by casatir** [comment]
As a side note, `src/pyodide-py/pyodide/console.py` will be re-created by #875 (or its children). I am working on it: everything is setup, just polishing the splitting into several PR.

**Pull request merged**
