### PR TITLE
Make JsBuffer into a subclass of JsProxy

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Review by phorward — CHANGES_REQUESTED** [review]
Can you please shortly explain why this change is useful?

**Comment by hoodmane** [comment]
The point is to support duck typing. I think the idea of duck typing is to be able to implement functions like:
```python
def isaduck(obj):
   return hasattr(obj, "quack") and iscallable(obj,quack)
```
If we implement quack on every JsProxy and just throw an error if we can't figure out how to quack:
```python
class JsProxy:
   def quack(self):
      if not hasattr(self.jsobject, "quack"):
         raise TypeError("Underlying Js object is not a duck")
      return self.jsobject.quack()
```
Now `isaduck(jsproxy)` _always_ returns true, but the `jsproxy` may be planning to raise a type error every time you call `jsproxy.quack()`. If we know that `quack()` has no side effects, then you can try:
```python
def isaduck(obj):
   try:
      obj.quack()
      return True
   except TypeError, NotImplementedError:
      return False
```
but this is a dangerous assumption. Thus I view this as a problematic antipattern. The point of this PR is to gradually move away from this antipattern towards conditionally implementing exactly the set of capabilities that the underlying javascript object can support.

**Review by phorward — APPROVED** [review]

**Comment by phorward** [comment]
Thank you, that sounds useful!

**Comment by hoodmane** [comment]
I suppose I should open an issue with the explanation I just gave and then further PRs in this direction I can cross reference against the issue.

**Comment by hoodmane** [comment]
Thanks @phorward!

**Pull request merged**
