### PR TITLE
Reorganized type conversions tests into separate files

### PR DESCRIPTION
**Pull request by hoodmane**
There are currently several issues (#780, #892) about the type conversions not working correctly. As far as I can tell there are no tests of the type conversions? The type conversions are a core part of Pyodide which deserve careful testing. I added a few tests.

Currently `test_list_from_py` and `test_dict_from_js` are failing which correspond to the examples respectively in issue #780 and in issue #892. I will open an issue with a proposal for a modification to the type conversions to fix these issues.

### CODE REVIEW

**Comment by rth** [comment]
Type conversion tests are generally in https://github.com/iodide-project/pyodide/blob/master/src/tests/test_python.py and those for numpy arrays are in packages/numpy/test_numpy.py.

Could you please check that the added tests are not redundant with those in `test_python.py` and we could indeed move conversion specific tests to a dedicated test file.

**Comment by hoodmane** [comment]
Ah of course, that is way more comprehensive, I just didn't know where to look for it.

> we could indeed move type conversion specific tests to a dedicated test file.

I will remove my redundant tests and copy the tests from `test_python` into `test_typeconversions`.

**Comment by hoodmane** [comment]
I removed the redundant tests for literals.

I added two new files: specifically for testing pyproxy and jsproxy, since these correspond one-to-one with the logic implemented in the c source files of the same name.

I also removed the new failing tests, since they contradict existing tests. Once this gets merged I can add a new PR changing the test suite to expect the behavior I described in proposal #900.

**Comment by rth** [comment]
> Currently [..] test_dict_from_js are failing

It seems to be passing it CI? Do you understand why?

Otherwise LGTM, thanks!

**Comment by hoodmane** [comment]
> It seems to be passing it CI?

Yeah I changed that:

> I also removed the new failing tests, since they contradict existing tests. Once this gets merged I can add a new PR changing the test suite to expect the behavior I described in proposal #900.

**Comment by rth** [comment]
Thanks @hoodmane!

**Pull request merged**
