### PR TITLE
Fix #327: Add sympy support

### LINKED ISSUE #327: is sympy gonna be supported?
are there any plans to add sympy in the future?

I'd like a CAS on JavaScript

### PR DESCRIPTION
**Pull request by mdboom**
This adds sympy.

Automatic rendering isn't working yet -- we'll need to set up our own hooks to make that work in Iodide, however I would suggest merging this anyway so we can iterate on getting the rendering to work in subsequent PRs.

Cc: @Kreijstal

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks for the review, @Kreijstal!

**Comment by utensil** [comment]
Is there a way to test the sympy support(without setting up a local development environment)? https://alpha.iodide.io/notebooks/222/ doesn't seem to support importing sympy yet. 

```python

Loading Python language plugin
Python plugin ready
from sympy import *
Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 1, in <module>
ModuleNotFoundError: No module named 'sympy'

_hiwire_throw_error()@https://alpha.iodide.app/pyodide-0.8.2/pyodide.asm.js:8:42138
{anonymous}()@wasm-function[355]:1239
{anonymous}()@wasm-function[382]:265
Object.__runPython()@https://alpha.iodide.app/pyodide-0.8.2/pyodide.asm.js:8:2033968
Object._runPythonInternal()@https://alpha.iodide.app/pyodide-0.8.2/pyodide.asm.js:8:45942
internal()@https://alpha.iodide.app/pyodide-0.8.2/pyodide.asm.js:8:46512
Object.runPythonAsync()@https://alpha.iodide.app/pyodide-0.8.2/pyodide.asm.js:8:46990
```

**Comment by Kreijstal** [comment]
you can test it if you know someone that hosts the sympy.js, data files and dependencies, on some server, for now.

**Comment by utensil** [comment]
It would be nice to have a iodie set up using a latest CircleCI build of pyodide.

I did try building pyodide using docker on my MBP but soon the fans started to run at full speed. 😂

**Comment by Kreijstal** [comment]
@utensil 
Here is my build of pyodide, scipy.data couldn't make it because it was too large for gist
https://gist.github.com/Kreijstal/08863a35451f71150ef33f7672015540

**Comment by utensil** [comment]
Thanks for sharing the build, but I don't know how to make use of it without a local pyodide server.

I tried on https://alpha.iodide.io/ with the following:

```python
%% fetch
js: https://gist.githubusercontent.com/Kreijstal/08863a35451f71150ef33f7672015540/raw/579d72d036f731f97be1c4c9f7ac4e4a43bedf07/sympy.js

from sympy import *
```

**Comment by mdboom** [comment]
We don't have the latest pyodide pushed to `alpha.iodide.io`.  We'll have to wait until it rides the rails.  I don't think there's any way to load a pre-released Python package into Iodide like this.

**Comment by jacobq** [comment]
> We'll have to wait until it rides the rails.

Is it possible to use `from sympy import *` on https://alpha.iodide.io today?

**Pull request merged**
