### PR TITLE
Add `version` field to pyodide in main.c

### LINKED ISSUE #922: Funny bug
In a fresh copy of `console.html`:
```python
>>> pyodide.version()
0.15.0
>>> pyodide.version()
Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 65, in eval_code
    return eval(compile(expr, "<eval>", mode="eval"), ns, ns)
  File "<eval>", line 1, in <module>
AttributeError: module 'pyodide' has no attribute 'version'
```
Hilarious. 

Not sure the best way to deal with `jspyodide` vs `pypyodide` for naming purposes.

### PR DESCRIPTION
**Pull request by hoodmane**
I made a couple of API changes:
1. `pyodide.version` is now a string constant not a function and no longer imports the `pyodide` python package into the main user namespace.
2. I added `pyodide.pythonVersion` which is the same as `sys.version`.

This fixes #922, but without really addressing it's root cause.

### CODE REVIEW

**Comment by hoodmane** [comment]
It looks like for some reason `selenium.run_js("return pyodide.pythonVersion;")` has an extra newline at the beginning. Could this be a `conftest` bug?

**Comment by hoodmane** [comment]
Nope, the test is functioning correctly, `pyodide.pythonVersion` is the empty string.

**Comment by rth** [comment]
+1 to make `version` a string constant. 

I'm less sure about adding `pythonVersion`. The python version is only one thing among  others that describe the pyodide contents, and we don't want to expose them all manually in JS. `pyodide.runPython("import sys; sys.version")` is fairly short and very versatile.

**Comment by hoodmane** [comment]
> I'm less sure about adding `pythonVersion`

Sounds reasonable, will remove it.

**Pull request merged**
