### PR TITLE
Fix #401: Better error message when using "import js"

### LINKED ISSUE #401: A more reasonable error when importing js
I realize that only `from js import something` is supported, but a more reasonable error message for `import js` would be very helpful:
```
import js
Error: TypeError: object of type 'NoneType' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 1, in <module>
SystemError: <JsImport object at 0x81c2e8> returned a result with an error set
```

### PR DESCRIPTION
**Pull request by mdboom**
Cc: @vadimkantorov

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Discussing the design: Should something like below be possible by implementing `getattr` in `js` and caching the output (so that js->python conversion hit happens only once)?
```python
import js
bytes = io.BytesIO(js.mydata_arraybuffer)
```

The semantics of equivalence of `from js import mydata_arraybuffer` and `import js; js.mydata_arraybuffer` is something most people would expect imho.

But certainly it's not a blocker.

**Comment by mdboom** [comment]
Interesting idea.  That wouldn't have even been possible on Python 3.6 when this project started, but might work with Python 3.7 given [PEP 562](https://www.python.org/dev/peps/pep-0562/).

**Comment by mdboom** [comment]
Indeed, PEP 562 works with extension modules here, and it turns out to make the implementation much easier -- we no longer need an import hook etc.

I've updated this PR -- I'd appreciate your review, @vadimkantorov

**Comment by vadimkantorov** [comment]
@mdboom Is js2python conversion enough low-overhead to be done at every attribute access? (if not, a whole array of issues around caching and cache invalidation arises)

**Comment by mdboom** [comment]
> @mdboom Is js2python conversion enough low-overhead to be done at every attribute access? (if not, a whole array of issues around caching and cache invalidation arises)

It depends on the type.  For large dictionaries and lists, it could be considerable.  But for functions (which is where this is most often used) it's pretty minimal.

However, I'd be wary of adding the complexity of caching here.  If the user wants to limit the conversions, they could just use `from js import ...` or `import js; x = js.x`.  Conversely, there are cases where you want the lookup to always be dynamic for consistency reasons, for example `window.title`.  So I think the right approach here is to not try to be too clever and let the user decide how to optimize.  I'd lean toward just documenting that behavior.

**Comment by vadimkantorov** [comment]
Does capturing a Python reference prevent the underlying JavaScript object from being destroyed by JavaScript's GC? (in case JavaScript for some reason deletes the corresponding global variable, while Python variable reference still exists)

**Comment by mdboom** [comment]
@vadimkantorov: I've added docs about the performance concern you raised.

**Pull request merged**
