### PR TITLE
PKG Update freesasa version to 2.1.0

### PR DESCRIPTION
**Pull request by smkm**
Updating to non-beta version.

### CODE REVIEW

**Comment by smkm** [comment]
`/bin/bash: clang-format: command not found`
I guess linting failure has nothing to do with the commit at least.

**Comment by rth** [comment]
@smkm could you please merge master in? the linting issue should be fixed now.

**Comment by smkm** [comment]
When merging, please squash merge.

**Comment by smkm** [comment]
Other than test-firefox OK.

**Comment by rth** [comment]
Thanks @smkm !

**Pull request merged**
