### PR TITLE
Fix #461: Handle member functions in `from js import ...`

### LINKED ISSUE #461: from js import fetch treats fetch as a free function
`fetch` is a member function of `window`.
However, using `from js import fetch` doesn't realize that and leads to the error:

`TypeError: 'fetch' called on an object that does not implement interface Window.`

For Reproducing the Error:
```
%%py

from js import document, Request, fetch, URL
img_tag = document.createElement('img')
req = Request.new('https://i.ibb.co/3f4yJQS/face4.jpg')

def func(response):
    return response.blob()

def func2(blob):
    objURL = URL.createObjectURL(blob)
    img_tag.src = objURL

fetch(req).then(func).then(func2)

document.body.appendChild(img_tag)
```

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by rth** [comment]
It looks like this makes `test_jsproxy_kwargs` test fail...

**Comment by mdboom** [comment]
Yeah -- I think this has broken the XHR API being used by micropip...  Something about detecting the member function vs. free function is still not quite correct...

**Comment by hoodmane** [comment]
@dalcde  @rth I think this should be closed, it's obsoleted by #972.

**Comment by hoodmane** [comment]
The one thing that looks interesting here is:
```javascript
EM_JS(int, hiwire_is_member_function, (int idobj), {
  var jsobj = Module.hiwire_get_value(idobj);
  // clang-format off
  return (
      typeof jsobj === "function" &&
      jsobj.prototype === undefined &&
      jsobj.constructor !== undefined
  );
  // clang-format on
});
```
but I don't know how that works.

**Comment by rth** [comment]
> I think this should be closed, it's obsoleted by #972.

You can indicate "Closes #972" in that PR description to auto-close this on merge.

**Comment by hoodmane** [comment]
Okay, #1126 was just merged which resolves #461 so I think this can be closed.

**Pull request closed without merging**
