### PR TITLE
WIP: Add spacy

### PR DESCRIPTION
**Pull request by msabramo**
From https://spacy.io/:

> spaCy is the best way to prepare text for deep learning. It interoperates seamlessly with TensorFlow, PyTorch, scikit-learn, Gensim and the rest of Python's awesome AI ecosystem. With spaCy, you can easily construct linguistically sophisticated statistical models for a variety of NLP problems.

### CODE REVIEW

**Comment by Juanlu001** [comment]
Weird errors coming from NumPy:

```
/home/circleci/repo/packages/spacy/build/spacy-2.1.3/include/numpy/npy_cpu.h:72:6: error: Unknown CPU, please report this to numpy maintainers with     information about your platform (OS, CPU and compiler)
    #error Unknown CPU, please report this to numpy maintainers with \
     ^
In file included from spacy/_align.cpp:608:
In file included from /home/circleci/repo/packages/spacy/build/spacy-2.1.3/include/numpy/arrayobject.h:15:
In file included from /home/circleci/repo/packages/spacy/build/spacy-2.1.3/include/numpy/ndarrayobject.h:17:
In file included from /home/circleci/repo/packages/spacy/build/spacy-2.1.3/include/numpy/ndarraytypes.h:8:
/home/circleci/repo/packages/spacy/build/spacy-2.1.3/include/numpy/npy_endian.h:42:10: error: Unknown CPU: can not set endianness
        #error Unknown CPU: can not set endianness
         ^
```

For comparison, I went to see the [logs for the pandas build](https://circleci.com/gh/iodide-project/pyodide/483) (#150) and the only differences I see are that `numpy` is listed as a dependency in `meta.yml` and that numpy itself is older (1.14.5).

I have no idea of what is wrong but in general I would love to see guidelines to contribute packages to pyodide.

**Comment by msabramo** [comment]
I suspect that the weird NumPy errors are happening because spaCy bundles its own copies of some NumPy headers and those headers are missing the patch https://github.com/iodide-project/pyodide/blob/master/packages/numpy/patches/add-emscripten-cpu.patch

I'm experimenting with adding that patch for spaCy.

**Comment by pk8189** [comment]
@msabramo how has your progress been adding spacy? any luck in the last few months?

**Comment by msabramo** [comment]
I haven't made any progress on this. I'm going to close it; someone is welcome to pick up the work if they are interested.

**Pull request closed without merging**
