### PR TITLE
Add sympy test

### PR DESCRIPTION
**Pull request by mgreminger**
Add test test to sympy package directory. Tests mpmath indirectly as well since sympy depends on mpmath.

### CODE REVIEW

**Comment by rth** [comment]
Thank you @mgreminger ! We are currently trying to avoid packaging pure python packages to reduce the maintenance burden on pyodide, as those can be easily loaded from PyPi directly https://github.com/iodide-project/pyodide/issues/643

We can merge this as is as a temporary solution however could you please report the issue of missing pure python wheels on PyPi to antlr4-python3-runtime and see if they could upload them. If they do, we could still include tests from this PR, but after installing this packages from PyPi.

**Comment by mgreminger** [comment]
@rth, thanks for the feedback. It does makes sense to not include pure python packages and I now understand why micropip wasn't working for antlr4. My use case is the same that @teonbrooks brings up in the discussion for #643 where I'm loading the .js and .data files directly for an app that will eventually be an electron app. Now that I have the build environment setup, I'm able to build these files for antlr4. However, it would be nice to be able to build the .js and .data files for a pure python pip package without having to create an entire pyodide build environment. I'm not sure how feasible this is without looking more into how the build process works for pure python packages.

For this PR, I propose that I remove everything except for the first sympy test since this would add some test coverage for sympy and mpmath that isn't there currently. Otherwise, I'll remove the antlr4 package and I'll remove the parse_latex test that depends on antlr4. Does this seem like a good plan?

**Comment by teonbrooks** [comment]
@rth I just saw in https://github.com/iodide-project/pyodide/pull/727 that you can load Python wheels in Pyodide. If we are working in node, could we then just download the wheels and serve it within an electron app?
If that workflow would work, that would be the best case for everyone.

**Comment by mgreminger** [comment]
@teonbrooks, that's a good point. I hadn't noticed that before, thanks for pointing it out. Pointing to a local wheel will work for my use case since I'm still at the stage of using a local web server. Not sure how it will work with electron since I haven't starting converting my project to electron yet.

**Comment by rth** [comment]
>  If we are working in node, could we then just download the wheels and serve it within an electron app?

@teonbrooks Assuming micropip works with node I would say so, but I haven't used node much. We would still need to make the main pyodide package loadable in node though I think https://github.com/iodide-project/pyodide/pull/183 (and `file_packager.py ` changed in that PR is also used used to package micropip BTW). So pure python wheels wouldn't really address the initial issue of the node support...


> Does this seem like a good plan?

@mgreminger yes, sounds good.

**Comment by rth** [comment]
Thanks @mgreminger!

**Pull request merged**
