### PR TITLE
Replace var ==> let and added semicolons to the ends of some js lines.

### PR DESCRIPTION
**Pull request by hoodmane**
Automatically replaced all instances of `var` with `let` via:
```sh
find src -type f -name "*.js" -or -name "*.html" -or -name "*.c"  -or -name "*.h" -or -name "*.py" -or -name *.md | xargs sed -E -i 's/\bvar\b/let/g'
```
and then again to the docs folder. Probably should wait to merge this until after some of the other PRs since it's easy to merge them into this.

### CODE REVIEW

**Comment by hoodmane** [comment]
This is working toward using modern javascript, related to #911. Another good thing would be to use async/await in `pyodide.js`. Unfortunately `EM_JS` seems to not support modern javascript though.

**Comment by dalcde** [comment]
See also #792. I think overall we should look into moving large EM_JS chunks to independent javascript files, e.g. `pyproxy_init`, giving us access to better tooling etc.

**Comment by rth** [comment]
Have you managed to identify  why the CI is failing?  There are some conflicts as well.

**Comment by hoodmane** [comment]
> Have you managed to identify why the CI is failing?

The issue is here:
```javascript
  let package_name_regexp = '[a-z0-9_][a-z0-9_\-]*'
  let package_uri_regexp =
      new RegExp('^https?://.*?(' + package_name_regexp + ').js$', 'i');
  let package_name_regexp = new RegExp('^' + package_name_regexp + '$', 'i');
```
==> error `package_name_regexp` redeclared

**Comment by rth** [comment]
> The issue is pyodide.js lines 17--20:

That would be easy to fix, wouldn't it? Otherwise this should be good to merge once the CI passes.

**Comment by hoodmane** [comment]
Well now the 6 webworker tests fail and the others pass.

**Comment by hoodmane** [comment]
@dalcde This failure is still pretty useless.

**Comment by hoodmane** [comment]
Furthermore I think this error is the fault of `conftest.py`. Running one specific test
`pytest -k "fire and destroy" src/tests/test_pyproxy.py`
locally gives the same error:
`conftest.JavascriptException: ReferenceError: languagePluginLoader is not defined`

Repeating the test manually in `console.html` by executing the following in browser console:
```javascript
pyodide.runPython(`
        class Foo:
          bar = 42
          def get_value(self, value):
            return value * 64
        f = Foo()
`)
let f = pyodide.pyimport('f');
console.assert(f.get_value(1) === 64);
f.destroy();
f.get_value();
```
Test works as expected:
```javascript
pyodide.asm.js:8 Uncaught Error: Object has already been destroyed
    at Object.getPtr (pyodide.asm.js:8)
    at Object.get (pyodide.asm.js:8)
    at <anonymous>:11:3
```

**Comment by hoodmane** [comment]
Oh interesting, every single firefox test failed but only six chrome ones failed (probably due to real problems).

**Comment by hoodmane** [comment]
In chrome all the webworker tests failed with nondiagnostic timeout errors (but webworker-specific test failures never give diagnostic error messages).

**Comment by dalcde** [comment]
Were we previously genuinely relying on the semantics of var here? What happens if you revert back to var languageLoaderPlugin = ... ?

**Comment by hoodmane** [comment]
I think `var` automatically defines it on the global object but `let` scopes it and so you need `window.languagePluginLoader = ...`

**Comment by hoodmane** [comment]
Confirmed that converting back to `var` makes it so that firefox and chrome fail the same set of tests. Will try `globalThis.languageLoaderPlugin` next.

**Comment by hoodmane** [comment]
As expected, `globalThis.languageLoaderPlugin` works. Thanks for your help @dalcde!

**Comment by hoodmane** [comment]
So now exactly the webworker tests fail. I'm not really sure yet what the best way to test this manually is. 

I think we need to make a version of `console.html` that uses the webworker to enable manual testing of webworkers.

**Comment by hoodmane** [comment]
I'm really surprised how hard this is and how easy #1080 was.

**Comment by hoodmane** [comment]
Well @dalcde's refactor of `pyodide.js` removed most of the `var`s so hopefully now this will work?

**Review by rth — APPROVED** [review]

**Pull request merged**
