### PR TITLE
Update jedi and parso to 0.17.2 and 0.8.0 resp

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Comment by rth** [comment]
Thanks @dalcde ! Generally LGTM. One concern is that latest version of jedi increased by 40% in size to (1.4MB compressed) and so we should probably stop including it in pyodide by default, and instead keep it as a normal package that can be loaded when needed.

The only think is that I'm not sure why CI didn't trigger, investigating that now.

**Comment by rth** [comment]
Could you please push an empty commit to this PR (`git commit --allow-empty`)? I'm hoping the CI issue was temporary (it works in other PRs now).

**Comment by dalcde** [comment]
Is there any reason jedi and parso are built manually instead of via a `meta.yaml` file? If it is purely historical, I might as well make the change here.

**Comment by rth** [comment]
OK, so closing and re-opening the PR finally triggers the CI (https://github.com/iodide-project/pyodide/issues/811). Not  sure what's happening there. 

> Is there any reason jedi and parso are built manually instead of via a meta.yaml file? If it is purely historical, I might as well make the change here.

As far as I know it was done initially to have auto-completion by default in iodide and make the  [`pyodide.get_completions`](https://pyodide.readthedocs.io/en/latest/python-api/pyodide.get_completions.html#pyodide.get_completions) function work. I think we should wait for https://github.com/iodide-project/pyodide/pull/792 to be merged, and then make jedi an optional package.

Currently packages use `meta.yaml` and C dependencies or anything that is needed when the main pyodide package is built use Makefiles. I think we could try to move them to `meta.yaml` eventually as well https://github.com/iodide-project/pyodide/issues/713 though it's not critical now.

**Pull request merged**
