### PR TITLE
Increase heap size to 1GB

### PR DESCRIPTION
**Pull request by mdboom**
@teonbrooks reported on Gitter that a Pandas notebook was running out of memory loading a 13MB json file.  Pandas is way too heavy weight for what it does, and it's kind of amazing that it can't do that in half a GB of memory.  Upping it to 1GB is the easy fix for now, but longer term I would like to find a way to modularize pandas or decrease the Cython-generated code size.

Note that #152 also makes the notebook work, but that approach won't work on Chrome and is measurably slower than without.

### CODE REVIEW

**Comment by rth** [comment]
Interesting! I have not realized that only half a GB or memory was available by default.

Posting @teonbrooks 's the error traceback for future reference,
> ```
> abort("Cannot enlarge memory arrays. Either 
> (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 536870912,
> (2) compile with -s ALLOW_MEMORY_GROWTH=1 which allows increasing the size at runtime, or
> (3) if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 ").
> Build with -s ASSERTIONS=1 for more info.
>  ```

Even 1GB would be fairly little for a number of real life applications, at the same time allocating that fixed amount of memory is also not great (I haven't checked yet if that is happening).

Wouldn't `ALLOW_MEMORY_GROWTH=1` work better in this case? According to emscripten [docs](https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html?highlight=allow_memory_growth#memory-growth) there should be little overhead (if it works).

**Comment by rth** [comment]
As you said [`settings.js`](https://github.com/kripken/emscripten/blob/89d4ae23e5149eebcf64181bdd74e88cfae568fc/src/settings.js) is even more detailed about different parameters than the docs, here in particular the comment about `ALLOW_MEMORY_GROWTH`,
> in wasm it is efficient and should be used whenever relevant.
                             // See https://code.google.com/p/v8/issues/detail?id=3907 regarding
// memory growth performance in chrome.

**Comment by mdboom** [comment]
Interesting.  That comment in settings.js is new since I last looked.  I'll file an alternative PR that sets ALLOW_MEMORY_GROWTH and let the tests run over it for comparison.  (That might give a rough idea of performance differences, too.)

**Comment by mdboom** [comment]
Closing in favor of #155.

**Pull request closed without merging**
