### PR TITLE
Update MNE package

### PR DESCRIPTION
**Pull request by teonbrooks**

### CODE REVIEW

**Comment by mdboom** [comment]
It looks like this version of `mne` imports `multiprocessing` at import time, which Pyodide doesn't like :)  Probably need to do the `multiprocessing` import lazily (which would require a change to mne)

**Comment by teonbrooks** [comment]
i was both the person who made the initial fix upstream and now broke with new code i added later 🤦🏾‍♂️

**Comment by teonbrooks** [comment]
related pr: https://github.com/mne-tools/mne-python/pull/6448/

**Comment by rth** [comment]
I imagine this needs to wait for the next mne release then?

**Comment by teonbrooks** [comment]
yeah, I will close for now and will reopen when we do a backport release

**Comment by teonbrooks** [comment]
backport for mne was released and I was able to upgrade the package.

**Pull request merged**
