### PR TITLE
TST: Test eval_code_async

### PR DESCRIPTION
**Pull request by hoodmane**
I removed the `NotImplementedError`s and added tests that show that `eval_code_async` works as advertised.

### CODE REVIEW

**Comment by hoodmane** [comment]
@casatir Can you review this?

**Review by phorward — APPROVED** [review]
Hello @hoodmane, this looks good for me, and I already merged the current master and fixed merging bugs.

When @casatir and @oeway had a look on this, we can merge it.

**Comment by hoodmane** [comment]
Thanks @phorward. If @casatir / @oeway don't have time to look at this, I think it's fine to merge this without their approval (after all these are just tests). Possibly @rth or @dalcde can look at it and decide?

**Review by rth — APPROVED** [review]
Thanks ! LGTM, as well.

**Pull request merged**
