### PR TITLE
Automated deployment to Netlify

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by rth** [comment]
Using netlify for deployment would be great! The CI netlify job doesn't seem to be running though. Are you sure it was enabled?

**Comment by mdboom** [comment]
The netlify job won't start (or even show up) until after the build is complete.  And none of this will run on a PR (for security reasons), so I just merged in order to start testing on master.  This will probably take a few iterations to get right, but shouldn't (hopefully) interfere with any other functionality in the meantime.

**Comment by mdboom** [comment]
This seems to be working now.  It is set up to only deploy from tags, not master.  Documentation updates coming next week.

**Comment by SimonBiggs** [comment]
Out of curiosity what's the web address of this deployment?

**Comment by mdboom** [comment]
@SimonBiggs: That's TBD as I work through all the details and make sure everything is working as we need.  There will be a follow-up documentation PR about this once things settle.

**Comment by mdboom** [comment]
This is now documented [here](https://github.com/iodide-project/pyodide/blob/master/docs/using_pyodide_from_javascript.md)

**Comment by SimonBiggs** [comment]
Thanks for that. I notice you haven't recommended its use. I think I might
just stick to my personaly hosted version at https://pyodide.pymedphys.com

... I might also drop different versions under version directories to
overcome caching issues...

**Comment by SimonBiggs** [comment]
Also once you've got some documentation at that site it might be worth checking in with Netlify if they're happy with that usage. Unfortunately, because all I was hosting at that site was the pyodide files and not a website they asked that I pull it down. So I moved back to GitHub pages and just dropped scipy given it's file size.

**Comment by SimonBiggs** [comment]
I imagine if you have notebooks, documentation, and the pyodide files, they hopefully might look far more kindly on it...

**Pull request merged**
