### PR TITLE
Add pyodide-interrupt package

### PR DESCRIPTION
**Pull request by dalcde**
This package was written so that one can interrupt python execution in pyodide, c.f. #676 and the package README (this is the crappy-python-multitasking module mentioned by @hoodmane, with a nicer name).

### CODE REVIEW

**Comment by rth** [comment]
Interesting thanks! Could you please add an entry to the changelog with a short description, possibly a minimal example and a link to this package's github repo?

**Comment by hoodmane** [comment]
I will make a MWE for this with some explanations.

**Comment by matham** [comment]
>MWE

Megawatt equivuilant? Microsoft web expreasion?

>add example

If you add an example, you should probably make sure to very strongly warn that the callback can be called at any random place and from any thread (when threads are enabled)  so it should access as little Python state as possible because it could be in the middle of modifying that state.

**Comment by hoodmane** [comment]
By MWE I meant "Minimal Working Example" sorry.

> If you add an example, you should probably make sure to very strongly warn that the callback can be called at any random place and from any thread (when threads are enabled) so it should access as little Python state as possible because it could be in the middle of modifying that state.

Good point. All I want the callback to do is check if an interrupt has been requested and if an interrupt has been requested raise a `KeyboardInterrupt`. Even this can cause trouble: if the `KeyboardInterrupt` is raised during import of a package, it can leave the package in a permanently broken partially initialized state. I believe that this issue is also present in native Python repls, but it takes longer to import packages in Pyodide so it comes up more.

**Comment by rth** [comment]
Thanks! The current changelog entry LGTM, it's probably indeed better just to link to your packages, that way it you change something in the API the changelog won't have invalid examples.

We can merge, unless you want to make another PyPi release with added warnings in the readme?

**Comment by hoodmane** [comment]
I think it's okay as-is, I don't expect most people to use this in an off-label way anyways.

A working example is probably too complicated for inclusion in your changelog in any case: at the very least, it will require one file for the worker, one file for the main thread, and some boilerplate logic to handle the message passing.

**Comment by matham** [comment]
>Even this can cause trouble: if the KeyboardInterrupt is raised during import of a package

Not completely relevant, but I found the [trio author's exposition](https://vorpus.org/blog/control-c-handling-in-python-and-trio/) about handling `KeyboardInterrupt` really interesting.

**Comment by hoodmane** [comment]
@matham Thanks for the link, I agree it's extremely interesting.

**Pull request merged**
