### PR TITLE
BUGFIX: Bind functions to window on `from js import func` (#461)

### LINKED ISSUE #461: from js import fetch treats fetch as a free function
`fetch` is a member function of `window`.
However, using `from js import fetch` doesn't realize that and leads to the error:

`TypeError: 'fetch' called on an object that does not implement interface Window.`

For Reproducing the Error:
```
%%py

from js import document, Request, fetch, URL
img_tag = document.createElement('img')
req = Request.new('https://i.ibb.co/3f4yJQS/face4.jpg')

def func(response):
    return response.blob()

def func2(blob):
    objURL = URL.createObjectURL(blob)
    img_tag.src = objURL

fetch(req).then(func).then(func2)

document.body.appendChild(img_tag)
```

### PR DESCRIPTION
**Pull request by hoodmane**
Instead of making ad-hoc duplicate definitions of `getattr` and `dir` in `jsimport.c`, make a `JsProxy` wrapping `window` and then define `JsImport_GetAttr` and `JsImport_Dir` to be transparent passthroughs to `JsProxy_GetAttr` and `JsProxy_Dir`. (This current implementation of `JsImport_Dir` leaves out some fields that are on the actual `PyModule` object, but the previous implementation also leaves those out. 

I plan to rewrite this whole file anyways in #972, this is just the minimal change that fixes the bug.
Resolves #461.

### CODE REVIEW

**Comment by dalcde** [comment]
Can you add a test for this?

**Comment by hoodmane** [comment]
About to, just checking if they actually work first.

**Comment by hoodmane** [comment]
I have a bunch of tests that only work with both this and #1124, so I have to sort through carefully to find the ones that test just this bug separately.

**Comment by hoodmane** [comment]
Currently this always crashes on initialization.

**Comment by hoodmane** [comment]
Test failures are expected: this won't work without #1124 being applied first. I guess I'll merge that here now so that the tests can pass.

**Comment by hoodmane** [comment]
@rth @dalcde I added `pytest.mark.xfail` to the test to show that #261 has been resolved because this bug complex also interacts with #974 which I have a fix for in #1033 so I figure we can re enable the key word arguments test when we merge #1033.

**Review by dalcde — APPROVED** [review]

**Comment by dalcde** [comment]
@hoodmane `test_jsproxy_call_kwargs` is currently failing

**Comment by hoodmane** [comment]
Right this is because `JsBoundMethod_Call` does not implement the keyword arguments handling but this change makes it so that all functions are always wrapped in `JsBoundMethod` and never in `JsProxy`. Correct solution is to move `JsProxy_Vectorcall` and `JsProxy_New` to `JsBoundMethod` and also perhaps to rename `JsBoundMethod` to `JsMethod` or something.

**Comment by hoodmane** [comment]
@dalcde correctly fixing `test_jsproxy_call_kwargs` is moderately complicated so I think the best thing is to `xfail` it here and open a second PR that fixes it.

**Comment by hoodmane** [comment]
Funnily enough, the last attempt at this #461 ran into exactly the same problem that it broke `test_jsproxy_kwargs`. I guess it's not surprising.

**Comment by dalcde** [comment]
>@dalcde correctly fixing `test_jsproxy_call_kwargs` is moderately complicated so I think the best thing is to `xfail` it here and open a second PR that fixes it.

It *was* working before this PR though

**Comment by hoodmane** [comment]
> It *was* working before this PR though

Yes, do you prefer: 

* a moderate-complexity set of changes added to this PR, or
* same changes in a separate PR?

I guess I can just `git checkout -b` and open a separate PR with more changes on this same branch and then you can take your pick.

**Comment by dalcde** [comment]
I would prefer a fix in a separate PR, assuming the fix doesn't depend on this. Then this can be merged after the fix is merged.

**Comment by hoodmane** [comment]
The fix will break ~15 tests until this one is merged.

**Comment by dalcde** [comment]
Then perhaps, as you said, a separate PR on top of this, and then I can merge them consecutively? I would very much prefer master to not regress, but it would be nice to logically separate the changes in history.

**Comment by hoodmane** [comment]
Yeah, this is a pretty tricky tangle of changes. Will do that.

**Pull request merged**
