### PR TITLE
Refactor wasm_backend.py into 3 components

### PR DESCRIPTION
**Pull request by madhur-tandon**
Closes https://github.com/iodide-project/pyodide/issues/447

`browser_backend.py` contains classes that will be common to both the backends.
The class `FigureCanvasWasm` has a `draw` method that will need to be implemented by the backends. Similarly, the method `download` of the class `NavigationToolbar2Wasm` will also require an explicit implementation.

### CODE REVIEW

**Comment by madhur-tandon** [comment]
@mdboom The `broswer_backend.py` file contains the classes `FigureCanvasWasm` and `NavigationToolbar2Wasm` along with the class `TimerWasm`. 

The respective backends can extend the classes `FigureCanvasWasm` and `NavigationToolbar2Wasm` and while doing so, they populate their own `draw()` method (of `FigureCanvasWasm`) and the `download()` method of `NavigationToolbar2Wasm`. The class `TimerWasm` is shared as it is.

The individual `backends` also contain an explicit implementation of a class derived from `FigureManagerBase`.

This allows us to create the new backends easily while reusing the common functionality present in `browser_backend.py`

**Comment by mdboom** [comment]
Oh, also, let's not `[ci skip]` this one.  Existing tests that cover the `wasm_backend.py` should run to confirm we're not breaking existing functionality.

**Comment by madhur-tandon** [comment]
Sure, I will amend the commits to not use `[ci skip]`

Moreover, I probably forgot to add the `meta.yaml` file, I am adding it now. I also think that `meta.yaml` should contain the copy command to all the 3 files. We anyways use just one of them (that is defined by `setup.cfg`).

I changed the definition from `pass` to `raise NotImplementedError` but didn't test it, sorry about that. Should we let it remain as `pass` or should `raise NotImplementedError` be used?

**Comment by mdboom** [comment]
> Moreover, I probably forgot to add the meta.yaml file, I am adding it now. I also think that meta.yaml should contain the copy command to all the 3 files. We anyways use just one of them (that is defined by setup.cfg).

We'll want to have all three.  The `copy` section defines which files end up in the matplotlib package.

> I changed the definition from pass to raise NotImplementedError but didn't test it, sorry about that. Should we let it remain as pass or should raise NotImplementedError be used?

I like the idea of it raising `NotImplementedError`.  Something is going wrong though because it's ending up calling this rather than the override in `FigureCanvasAggWasm`.

**Comment by madhur-tandon** [comment]
@mdboom So apparently, using just `pass` instead of `raise NotImplementedError` works. If we really wanna use the `NotImplementedError`, I shall look into this, but it's gonna take some time since the whole manual testing process is kinda long.

**Comment by madhur-tandon** [comment]
@mdboom I have checked it out. It turns out that there is nothing we can do about this except using `pass`. This is because the `draw()` method of `FigureCanvasWasm` will always get called after the `draw()` method of `backend_agg.FigureCanvasAgg`. This stuff is related to MRO aka Method Resolution Order. I have read an answer that describes our exact same scenario here: https://stackoverflow.com/questions/3277367/how-does-pythons-super-work-with-multiple-inheritance

I have also played around with the code here (in Python2) : https://pastebin.com/ezTyZ5Wa

In Retrospect, the `draw()` method of `FigureCanvasWasm` WILL get called eventually since this is a case of Multiple Inheritance and python's MRO follows stuff from left to right. Since it is defined to `raise and error`, it halts further execution while using `pass` allows us to skip over it.

**Pull request merged**
