### PR TITLE
Remove incorrect getattr limitation from docs

### PR DESCRIPTION
**Pull request by hoodmane**
typeconversions.md lines 88 - 112 is wrong. I added a test showing the actual (correct) behavior and removed the wrong description from the docs.

### CODE REVIEW

**Comment by dalcde** [comment]
Can you add a test for accessing an attribute that simply never existed, instead of being `del`'d?

**Comment by hoodmane** [comment]
@dalcde Done.

**Comment by dalcde** [comment]
Looks good to me

**Review by rth — APPROVED** [review]
Thanks @hoodmane !

**Pull request merged**
