### PR TITLE
WIP Replaced -O3 with -O2 option for testing 

### PR DESCRIPTION
**Pull request by aditj**
This is a work in progress pull for testing the behaviour and benchmarking the performance of our build time with different optimisation options . See [issue](https://github.com/iodide-project/pyodide/issues/234)

### CODE REVIEW

**Comment by rth** [comment]
Thanks @aditj . Was there some notable results with this experiment? If you don't intend to work on this PR anymore free to close it.

**Comment by aditj** [comment]
I am really sorry @rth! 
I got busy and almost forgot about this :sweat: 
If you dont mind can I keep this open for another couple of weeks , I'll try to experiment if I get time other wise I'll close it.

**Comment by rth** [comment]
Sure, thank you!

**Comment by aditj** [comment]
Sorry, @rth Hope you understand :)

**Comment by rth** [comment]
No worries, thanks for investigating @aditj !

**Pull request closed without merging**
