### PR TITLE
PKG Added the python-sat package

### PR DESCRIPTION
**Pull request by alexeyignatiev**
Hi all. Please, consider merging this pull request. Here I added the [PySAT toolkit](https://pysathq.github.io/) (represented as `python-sat` package). It is designed for easy prototyping with SAT oracles, i.e. automated reasoners for propositional logic. The toolkit provides interface to a number of state-of-the-art SAT solvers and also other modern SAT-related technology.

### CODE REVIEW

**Comment by rth** [comment]
Thanks! There is a build failure, cf circle CI logs..

**Comment by alexeyignatiev** [comment]
Yep, I am going to fix that. :)

**Comment by alexeyignatiev** [comment]
@rth, as far as I can see, the build check was successful this time but something wrong happened with the `test-firefox` check. I am completely new to this. Does this mean something is wrong with my particular package or it is something to be expected?

**Comment by rth** [comment]
Thanks @alexeyignatiev , you can ignore the failure due to lxml (cf https://github.com/iodide-project/pyodide/pull/544#issuecomment-652374731)

Overall this looks good, but I'm a bit concerned by the 8kL  patch in `proper_build.patch`. Is there a chance some of it would be included upstream? I see you have made a several updates to python-sat lately, would building with master work better? You can point the URL to a .tar.gz from a github commit in `meta.yaml`.

Also maybe does `pysat/__init__.py` import those compiled solvers? If not might be useful to also test a few of the other import paths.

**Comment by alexeyignatiev** [comment]
Hmm, the 8kL patch is quite weird indeed, thanks for noticing! I will check why I got that and let you know if there is a better solution on my side (at first glance, the patch should be much smaller). Building should be working fine in the latest versions of the python-sat toolkit. Thanks for the pointers regarding the use of master! I am not sure if that is needed though. :)

**Comment by alexeyignatiev** [comment]
Hi @rth. I've updated the package. The 8kL patch is now fixed and looks as it should. Can this be merged?

**Comment by rth** [comment]
@alexeyignatiev Looks like the sha256sum for the download changed,
```
sha256sum python-sat-0.1.6.dev3.tar.gz
9041712e9cbc33dad6034182bf500e5832b97dd8157d2c36628a15f86cef3234  python-sat-0.1.6.dev3.tar.gz
```
and the build started to fail. Maybe the git tag was moved? Would you mind making a PR to address that?

**Comment by alexeyignatiev** [comment]
Yes, that's my bad. I reuploaded the file an hour ago or so and haven't yet updated the sha256 sum here. The PR is [here](https://github.com/iodide-project/pyodide/pull/715).

**Pull request merged**
