### PR TITLE
Build six using usual build system

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Comment by dalcde** [comment]
The list of packages requiring six are obtained by
```
grep -r six packages/*/build/*/{setup.py,setup.cfg,*requirement*}
```

**Comment by dalcde** [comment]
After this PR is merged, we can get rid of some six dependencies by upgrading the packages

**Review by rth — APPROVED** [review]
Thanks! LGTM, assuming CI passes.

**Comment by rth** [comment]
We also need to update the docs,
```bash
$ rg -A1 six docs/
docs/loading_packages.md
4:Only the Python standard library and [six](https://pypi.org/project/six/) are 
5-available after importing Pyodide.
```

**Pull request merged**
