### PR TITLE
Re-organize changelog by submodule

### PR DESCRIPTION
**Pull request by rth**
The changelog for this version is getting long, and it should make it easier to find things.

Rendered version: https://21664-122663163-gh.circle-artifacts.com/0/home/circleci/repo/docs/_build/html/project/changelog.html

### CODE REVIEW

**Comment by rth** [comment]
Hmm, it's a lot of colors, maybe we should at least make the badges to use more pastel colors, not sure.


image

**Comment by hoodmane** [comment]
It'd be nice to increase the right margin on the badges if possible. As is the text around the badges looks pretty crowded.

**Comment by rth** [comment]
Added some right margin, and added opacity so that badges are a bit less bright. Rendered verion [here](https://21771-122663163-gh.circle-artifacts.com/0/home/circleci/repo/docs/_build/html/project/changelog.html). What do you think?

**Comment by hoodmane** [comment]
Looks good to me. Definitely better with the opacity.

**Pull request merged**
