### PR TITLE
Feature/add statsmodels

### PR DESCRIPTION
**Pull request by inesani**
Closes https://github.com/iodide-project/pyodide/issues/514

I have opened this PR in order to add the statsmodels package.

### CODE REVIEW

**Comment by rth** [comment]
Thanks @inesani ! The current error is,

> scipy is installed but older (0.17.1) than required (0.18). You must manually
upgrade scipy before installing or install into a fresh virtualenv.

The current scipy version is indeed a bit old due to constraints with Fortran https://github.com/iodide-project/pyodide/issues/184 . Though it may very well be that scipy 0.18.X would also build (worth a try but a lot of patches would need to be re-applied). A workaround for this PR could be to use statsmodels from a couple of versions before the last one that still supported scipy 0.17.1.

**Comment by inesani** [comment]
Thank you @rth. I have taken into account your previous indications and the integration has gone forward. I am now having a `selenium.common.exceptions.TimeoutException` error which i don't know how to resolve. Any thoughts?

**Comment by rth** [comment]
Retriggered CI to see if the error if reproducible.

**Comment by inesani** [comment]
In case it helps, the solution for making it work locally and avoid the error on the import in chrome test was to manually add statsmodel to the packages.json file. It is working fine now on both Chrome and Firefox.

**Pull request merged**
