### PR TITLE
Fix #406: Correctly convert a raw ArrayBuffer to Python memoryview

### LINKED ISSUE #406: arrayBuffer: js2python conversion might be faulty
It might be that js2python conversion is broken for `arrayBuffer`:
```
%% fetch
arrayBuffer: data=https://cors-anywhere.herokuapp.com/https://github.com/schitaytesami/lab/releases/download/data/electionsData.npz
%% js
var data_uint8 = new Uint8Array(data);
%% py
import numpy as np
import io
from js import data, data_uint8, Uint8Array
np.load(io.BytesIO(data_uint8)) # ok
%% py
np.load(io.BytesIO(Uint8Array.new(data))) # error
```

For context: recent posts in https://github.com/iodide-project/iodide/issues/1686

### PR DESCRIPTION
**Pull request by mdboom**
Cc: @vadimkantorov

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Would the example in https://github.com/iodide-project/pyodide/issues/406 incur any data copy?
https://github.com/iodide-project/pyodide/pull/407/files#diff-6b8d95ac6432610e52334279969d6d8cR373 lets think some data copy would be done

**Comment by mdboom** [comment]
Yes, there would be data copy, since arrays accessed outside of the Wasm heap can't be accessed on the Wasm side.  I'm not sure there's a way around this, though, as you can't tell the browser's fetch where to fetch into.

One could probably use [readable streams](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams) to at least only have a smaller amount in memory at a given time.  And that's probably something that will be easier to do from Python once the `async` stuff in #245 shakes out.

**Comment by vadimkantorov** [comment]
Is copy incurred on the js2python side or python2js or both?

I.e. during `Uint8Array.new(data)`, will it happen that `data` is first converted js2python, then it's passed to Uint8Array's new (and converted back python2js), then Uint8Array is passed back js2python and copied a third time?

Does js2python of Uint8Array also incur a data copy?

**Comment by mdboom** [comment]
> Is copy incurred on the js2python side or python2js or both?

There is only one copy from the original arraybuffer that the fetch wrote to into the wasm heap.  After that, everything stays in the same place on the wasm heap and can be used from Python and Javascript interchangably, only with the low cost of building new data structures around a pointer to the same location in memory.

These are the "copy free" code paths in [python2js](https://github.com/iodide-project/pyodide/blob/master/src/python2js_buffer.c#L314) and in [js2python](https://github.com/iodide-project/pyodide/blob/master/src/jsproxy.c#L297).

**Pull request merged**
