### PR TITLE
Add style to matplotlib widgets

### PR DESCRIPTION
**Pull request by madhur-tandon**
Closes https://github.com/iodide-project/pyodide/issues/36

### CODE REVIEW

**Comment by madhur-tandon** [comment]
@mdboom @hamilton @wlach 
I have been able to implement the ``change colour on hover`` feature. This is indirectly done using events such as ``mouseenter`` and ``mouseleave`` (using the correct callbacks) as the ``:hover`` selector cannot be used directly. 

I have also used system fonts for buttons that contain text, specifically, for buttons ``pdf``, ``png`` and ``svg``.

As a proof that it works, I am attaching the following GIF:

ezgif com-video-to-gif

This should be ready to merge unless some minor changes are required. Please let me know, Thanks!

**Comment by mdboom** [comment]
I think as @hamilton suggested [here](https://github.com/iodide-project/pyodide/issues/36#issuecomment-453763892), it would be better to use CSS for this rather than Javascript, since then we can have animations and a generally smoother experience.  But I see why attaching styles to individual elements won't work for this since you can't use `:hover` that way.

It should be possible to add a `style` element to the page in the constructor which defines a new class (e.g. `matplotlib-toolbar-button`), with both `:hover` and non-hover states, and then just set the class on the buttons when they are built.  (Add a global variable to ensure that the `style` content is only added once).  There are cleaner solutions I could imagine, but those would require `iodide`-specific changes, and we want pyodide to continue to work without iodide if we can.

@hamilton: Do you agree with my suggestions?

**Comment by madhur-tandon** [comment]
@mdboom @hamilton I have updated the PR so as to use CSS instead of HTML DOM Events ``mouseenter`` and ``mouseleave``. The CSS added is defined in the constructor of ``FigureCanvasWasm`` class and is finally appended as a child to the ``root`` node of the figure. Since each new ``matplotlib`` figure has a different ID, thus the CSS defined in the ``style`` tag is added separately to each ``root`` element of different figures if any. I couldn't understand why we need a global variable to add this ``style`` tag only once as different figures have different IDs and each of them would need this ``style`` tag as they have their own set of buttons.

If we need to add this ``style`` tag only ONCE [aka by adding a global variable], where should we add it?

Lastly, there are 2 ways of doing this:

- a) Using CSS as done with the latest commit ``https://github.com/iodide-project/pyodide/pull/296/commits/15d8cd2d4496eddb57345619781de3d9ca31e3d2`` of this PR.
and
- b) Using HTML DOM Events as done in the 3rd commit ``https://github.com/iodide-project/pyodide/pull/296/commits/035d85043e4d3b23c1b66a258379d730237cd9a5`` of this PR.

According to me, both are fine and work well. Why are we preferring a) over b) though?

Anyway, I have implemented a). Please let me know if any changes are to be made. Thanks!

**Comment by mdboom** [comment]
We're preferring (a) because 1) it can handle animation of the changes of styles, and 2) reduces duplication by adding lots of CSS for each element, when they could much better be shared.  As a general principle, it's more efficient and extensible to use CSS when CSS can do the job.

The contents of a `<style>` tag apply anywhere in the document.  So having it in each matplotlib figure is unnecessary.  (There used to be a `scoped` attribute on `style` elements so you could say that that CSS only applied to a particular part of the DOM tree, but that has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style)).  It should ideally be added to `<head>` with some logic to make sure it's added only once.  You could use a global Python variable, or you could assign it an id and then do something like `if document.getElementById('matplotlib-figure-styles') is None: # ... add the style element`.

**Comment by madhur-tandon** [comment]
@mdboom I understand now. However, I am a bit unsure as to where the ``<head>`` element is in the ``wasm_backend.py`` file aka where can I locate it and then finally add the ``<style>`` tag using ``appendChild``. As far as I can look, the ``root`` element that's at the top of the hierarchy here is a ``div`` with a unique ID (such as ``matplotlib_54efcc0``) for that plot / figure. I shall look into it once again, do you have an idea though?

Also, is the current location [in the constructor of ``FigureCanvasWasm``] of the ``css`` added within ``"""`` fine? Or should I move it somewhere else?

**Comment by mdboom** [comment]
> However, I am a bit unsure as to where the <head> element is

It's just on the HTML DOM, so you can get it with `document.head`.  (It's a little hard to get your head around, but the DOM is fully accessible from Python).

> Also, is the current location [in the constructor of FigureCanvasWasm] of the css added within """ fine? 

It wouldn't hurt to make it its own private method (e.g. `_add_matplotlib_styles`) and then call that from the constructor.

**Comment by madhur-tandon** [comment]
@mdboom @hamilton Updated the PR, also checked it with a fresh build of ``matplotlib``. It works! Can you review?

**Pull request merged**
