### PR TITLE
Recycling hiwire keys

### PR DESCRIPTION
**Pull request by phorward**
hiwire is frequenly used to interchange values and objects between Python and JavaScript. Even when objects are deleted from hiwire.objects after usage, their key is never used again, and the offset is increased all the time until it might overflow when the site is executed for a very long time and with lots of interchanges.

This little improvement may avoid an overflow by re-using keys which already had been used before, using a list of recycled keys.

### CODE REVIEW

**Comment by rth** [comment]
Thanks @phorward ! There is a type error in `test_jsproxy` currently. Otherwise the approach makes sense.

> their key is never used again, and the offset is increased all the time until it might overflow when the site is executed

As far as I understand the `counter` is a number in JS, that would overflow at ~1e300? Or is it getting cast to int32 somewhere? Just curious: can we actually reach that in practice?

**Comment by phorward** [comment]
> There is a type error in `test_jsproxy` currently. 

Yep... I took a look on it and it seems to be something huger.

> As far as I understand the `counter` is a number in JS, that would overflow at ~1e300? Or is it getting cast to int32 somewhere? Just curious: can we actually reach that in practice?

No, its not casted to int32 somewhere, but when a lot of operations like function calls to JS-functions are done, every parameter, every args-tuple and every kwargs dict becomes one entry in this table which is immediately deleted after usage, and the counter is always increased. Therefore, at some time, it might overflow. But maybe I'm also wrong with my opinion and this pull request is awkward.

**Comment by dalcde** [comment]
My understanding of the existing code is that the counter loops back to 0 when the counter hits 2^31 (and searches for the unused indices). So unless you have 2^31 objects around, in which case you probably have larger issues, there is no risk of running out of counters. There might be a significant performance impact once this happens though.

*Side:* The counter is an number in JS, which means it can accurately represent integers up to 2^53. Afterwards, integers are not represented precisely, and adding 1 becomes a noop:
```js
>> 2 ** 53 == 2** 53 + 1
true
```
Thus, while it can "represent" numbers up to ~10^300, you really want to avoid that for the purposes of a counter.

**Comment by hoodmane** [comment]
I vote we should close this PR because the existing code already supports this:
```javascript
// Search for an available id 
while (_hiwire.objects.has(_hiwire.counter)) {
  _hiwire.counter = (_hiwire.counter + 1) & 0x7fffffff;
}
// allocate id
let idval = _hiwire.counter;
_hiwire.objects.set(idval, jsval);
// increment counter
_hiwire.counter = (_hiwire.counter + 1) & 0x7fffffff;
return idval;
```
The existing code doesn't work I don't think because in a few places the assumption is made that the key of an object is nonzero. If the counter ever hits 2^31 and wraps back to 0, it will assign an object with key 0 which will be glitchy.

I would kind of like to set 0 aside and use `return NULL` as an error code instead of `return JsError`.

**Comment by dalcde** [comment]
The easiest fix would be to occupy 0 with a dummy value, but we should probably stop making that assumption.

**Comment by phorward** [comment]
Hi @dalcde and @hoodmane, thank you for your further investigation on this, I've lost focus on it since a while, and I'm also of the opinion to close it for now.

**Pull request closed without merging**
