### PR TITLE
Upgrade cpython to 3.7.6

### PR DESCRIPTION
**Pull request by wlach**
Among other things, cpython has fixes which are needed to allow
compilation under MacOS X Catalina, where we can no longer have
headers in `/usr/include`.

### CODE REVIEW

**Comment by mdboom** [comment]
Looks like something pretty fundamental has gone wrong with the tests.  There have been significant changes to the test runner (`libregrtest`) between 3.7.0 and 3.7.6.  It looks like the tests are succeeding (`sys.exit(0)`), but then cleaning up something to do with threading is failing.  I'll check this out and see what I can discover...

**Comment by aseering** [comment]
@mdboom I'm curious if you've discovered anything here?

**Comment by aseering** [comment]
FYI I kicked off a bit of a brute-force test to see which Python version introduces this issue:
https://github.com/aseering/pyodide/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+%22Upgrade+cpython+to%22

**Comment by aseering** [comment]
Actually it looks to me like this test is failing on master right now as well?

**Comment by aseering** [comment]
@wlach I know there was a fix to master a couple weeks ago; do you think this PR might pass if it's rebased against latest master?  Would you mind if I rebased it to see?

**Comment by mdboom** [comment]
Sure -- please go ahead and rebase and let the tests re-run.

**Comment by aseering** [comment]
FYI I'm not sure I have read/write access to this repo?  I forked and rebased in my own repo; the rebase did not cause tests to pass:

https://github.com/aseering/pyodide/pull/1

So I'm trying a more incremental approach:

https://github.com/iodide-project/pyodide/pull/619

**Comment by rth** [comment]
> FYI I'm not sure I have read/write access to this repo? I forked and rebased in my own repo; the rebase did not cause tests to pass:

Yes the easiest if you want to work on this is to create a branch in your fork based on this one, and make a new PR.

**Comment by rth** [comment]
I have added a patch to libregrtest in stdlib that was making tests fail due to threading, but there are other tests failures that need investigation and possibly patching.

**Pull request closed without merging**
