### PR TITLE
PKG Add imageio

### PR DESCRIPTION
**Pull request by oeway**
This PR aims to add imageio package and enable it in scikit-image (disabled in https://github.com/iodide-project/pyodide/pull/866).

### CODE REVIEW

**Comment by oeway** [comment]
@hoodmane This is my first package, maybe you can help me checking what's going on in the CI, why it is failing?

Also I am wondering how can I run the test locally. I did `PYODIDE_PACKAGES="imageio" make` and it said `SUCCESS!`, then I try to run the test with `PYODIDE_PACKAGES="imageio" make test` but get an error `ModuleNotFoundError: No module named 'tests.test_emulate'`. What is the correct way to build and run test locally for a specific package?

**Comment by rth** [comment]
You can test a specific package with,
```
pytest packages/imageio/test_* -k firefox
```
for instance to run tests with Firefox.

**Comment by oeway** [comment]
I tested it locally with `pytest packages/imageio/test_* -k firefox` and it passes.

No idea why the CI fails, and I could figure out the error, can someone have a look? Thanks.

**Comment by hoodmane** [comment]
I looked at it but I have no clue either. It looks like it might not have compiled?

**Comment by oeway** [comment]
Get the CI passed by adding `requirements` with `numpy`, finally. The error message in the CI was confusing and I had to guess blindly.

**Comment by hoodmane** [comment]
I feel your pain, the CI error messages are often very confusing.

**Comment by oeway** [comment]
@rth Can we trigger a rebuild? the error in CI is about the core, doesn't seem to related to what I changed.

**Comment by hoodmane** [comment]
@oeway To trigger rebuild:
```sh
git commit --allow-empty -m "Rerun CI"
git push
```

**Comment by rth** [comment]
Thanks @oeway and @hoodmane !

**Comment by hoodmane** [comment]
This was all @oeway, I didn't contribute anything of value to this PR =)

**Comment by rth** [comment]
Answering questions in PRs is still very helpful.

**Pull request merged**
