### PR TITLE
Upgrade to Python 3.7.2

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by mdboom** [comment]
Ugh.  This seems to break scipy.

**Comment by rth** [comment]
Sorry, wrong button.

So the error is,
```
E           from .misc import *
E         File "/lib/python3.7/site-packages/scipy/linalg/misc.py", line 6, in <module>
E           from .lapack import get_lapack_funcs
E         File "/lib/python3.7/site-packages/scipy/linalg/lapack.py", line 362, in <module>
E           from scipy.linalg import _flapack
E       ImportError: Could not load dynamic lib: /lib/python3.7/site-packages/scipy/linalg/_flapack.so
E       CompileError: at offset 103036: byte size mismatch in elem section
```
hmm, not sure why changing the minor python version would make it fail. Could be an indication that the part related to lapack is a bit brittle.

**Comment by rth** [comment]
Trying to revive this PR, let's see if tests now pass. cc @aseering

**Comment by rth** [comment]
CI is green, merging. I think the original reason why this was failing is that some paths remained unchanged from 3.7.1 initially.

**Comment by mdboom** [comment]
\o/  Thanks, @rth!  This is awesome.

**Comment by aseering** [comment]
indeed, thanks @rth !

**Pull request merged**
