### PR TITLE
Fix compile error from methnoargs-signatures branch

### PR DESCRIPTION
**Pull request by hoodmane**
We were using `JsProxy_GetIter` as `.tp_iter` (signature is `unaryfunc` i.e., `PyObject* f(PyObject*)`) and to define a `METH_NOARGS`  `__iter__` method (signature should be `PyCFunction` i.e., `PyObject* f(PyObject*, PyObject*)`, second argument always `NULL`. In the standard library, iterables only define `tp_iter` and don't explicitly define an `__iter__` method so I just removed the `__iter__` method.

There is a similar issue with `.tp_as_async->am_await` which is a `unaryfunc` and `__await__` which is a `PyCFunction`. Again, it's nonstandard for builtin C types to define an `__await__` method so I removed it.

### CODE REVIEW

**Comment by hoodmane** [comment]
This time the CI is running =)

**Comment by hoodmane** [comment]
It's weird that there is no `tp_dir` actually. Indeed, looking at the standard library, extension modules with a `__dir__` function just define a `METH_NOARGS` method called `__dir__` like we do.

**Comment by hoodmane** [comment]
@rth Looks like a sporadic failure.

**Comment by rth** [comment]
Thanks for the explanation and the fix @hoodmane !

**Comment by rth** [comment]
It again failed at build time on master with,
```
src/core/jsproxy.c:419:14: error: incompatible pointer types initializing 'getiterfunc' (aka 'struct _object *(*)(struct _object *)') with an expression of type 'PyObject *(PyObject *, PyObject *)' (aka 'struct _object *(struct _object *, struct _object *)') [-Werror,-Wincompatible-pointer-types]
  .tp_iter = JsProxy_GetIter,
             ^~~~~~~~~~~~~~~
1 error generated.
```
while CI was fine here. Not really sure what's happening. Maybe resetting the CircleCI cache key would help.

**Comment by hoodmane** [comment]
Looks to me like it still has the old version -- could it be a problem
because I used the same branch for this pr as for the old version somehow
it didn't fetch the new commits correctly?

**Comment by hoodmane** [comment]
Looks like a problem merging #1176 with the partially merged version from
#1168. In particular, line 181 of jsproxy.c is wrong in master but it's
right at the tip of my branch. Will submit a third PR when I get back to a
computer and hopefully get it right on the third try.

**Comment by hoodmane** [comment]
Okay now #1177 should hopefully fix this problem actually for real this time...

**Pull request merged**
