### PR TITLE
Don't copy artifacts to root

### PR DESCRIPTION
**Pull request by dalcde**
Load them directly with --preload-file. Avoids issues such as #1069

### CODE REVIEW

**Comment by rth** [comment]
If you check the `check-size` setup in the build-core CI job,
```
-rw-r--r-- 1 root root  51M Jan 10 03:37 pyodide.asm.data
```
this is currently clearly including some folders that it shouldn't. Before it was,
```
-rw-r--r-- 1 root root 5.5M Jan 10 09:22 pyodide.asm.data
```

Otherwise the idea sounds good.

**Comment by dalcde** [comment]
If I didn't mess this up this should remove e.g. sqlite tests as well (#646)

**Comment by dalcde** [comment]
It's now 5.2 MB

**Comment by rth** [comment]
> It's now 5.2 MB

Great!

**Comment by rth** [comment]
Actually this might remove tests that we don't properly extract in the test package. See second point from https://github.com/iodide-project/pyodide/issues/646 but as far as I can tell we are not running them anyway (the number of tests run here and on master is the same), so this change should be OK.

**Pull request merged**
