### PR TITLE
Upgrade cpython to 3.7.3

### PR DESCRIPTION
**Pull request by aseering**
Let's keep pushing forward!

### CODE REVIEW

**Comment by aseering** [comment]
I've run this through tests a few times.  None of the runs have passed, but no single test has failed repeatedly, and most have looked like the memory issue that we've seen before.

**Comment by aseering** [comment]
... looks like it's not automatically running tests in this repo, though?

**Comment by rth** [comment]
Thanks @aseering ! Probably some issue with CircleCI. Pushed a commit to re-trigger, waiting for results.

**Comment by rth** [comment]
1 different failures in chrome and firefox each, but overall looks good. Will restart CI to be sure.

**Comment by rth** [comment]
So there are some failures on master, but in some other tests that in previous two commits. It's really unfortunate that test failures are so random.

**Pull request merged**
