### PR TITLE
Replace some scipy patches with sed

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Review by rth — APPROVED** [review]
Thanks ! For the other replacements e.g. `void f_dgemm(` to `int f_dgemm(` I'm not sure if it would be better to do them in a python script with regex or keep them as they are currently.

**Comment by dalcde** [comment]
Yeah that would be more complex. I thought to get the low-hanging fruit first.

Another thing we should look into is why this worked previously; we were compiling to wasm previously too so it cannot be a fundamental restriction of wasm

**Comment by rth** [comment]
> Another thing we should look into is why this worked previously

You mean with previous function signatures? Well it wasn't fully working. A number of scipy functions produced errors at runtime previously e.g. https://github.com/iodide-project/pyodide/issues/492 https://github.com/iodide-project/pyodide/issues/615

**Comment by dalcde** [comment]
Fair enough

**Comment by hoodmane** [comment]
Really cool how many of these old issues we've fixed recently!

**Review by phorward — APPROVED** [review]

**Pull request merged**
