### PR TITLE
Add package freesasa and add biopython missing requirement

### PR DESCRIPTION
**Pull request by smkm**
Solving Issue #691 

No patch required to function correctly.

image

Executed on the iodide/pyodide-env docker container

### CODE REVIEW

**Comment by rth** [comment]
Thanks @smkm ! How long does it take to build freesasa from sources? What concerns me is that the build take takes 1hour in this PR, while it takes 40min on master. I'll restart CI to see if it's some caching issue.

**Comment by smkm** [comment]
> Thanks @smkm ! How long does it take to build freesasa from sources? What concerns me is that the build take takes 1hour in this PR, while it takes 40min on master. I'll cancel and restart CI to see if it's some caching issue.
It only took like 30 seconds with 6 cores. It isn't a big application (source is under 200kb, compiled whl for linux 64 is under 500kb)

**Comment by smkm** [comment]
@rth I also found an issue on BioPython where it should have a requirement for Numpy.
Should I also commit it in my branch?

**Comment by rth** [comment]
> on BioPython where it should have a requirement for Numpy for its submodules but it doesn't.

Yes, please. Or you can open a new PR. As you prefer.

**Comment by smkm** [comment]
Done.

**Comment by smkm** [comment]
Build log for freesasa

```
running install
running bdist_egg
running egg_info
writing freesasa.egg-info/PKG-INFO
writing dependency_links to freesasa.egg-info/dependency_links.txt
writing top-level names to freesasa.egg-info/top_level.txt
reading manifest file 'freesasa.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'freesasa.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'freesasa' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/lib
creating build/temp.linux-x86_64-3.7/lib/src
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/classifier.c -o build/temp.linux-x86_64-3.7/lib/src/classifier.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/classifier_protor.c -o build/temp.linux-x86_64-3.7/lib/src/classifier_protor.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/classifier_oons.c -o build/temp.linux-x86_64-3.7/lib/src/classifier_oons.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/classifier_naccess.c -o build/temp.linux-x86_64-3.7/lib/src/classifier_naccess.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/coord.c -o build/temp.linux-x86_64-3.7/lib/src/coord.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/freesasa.c -o build/temp.linux-x86_64-3.7/lib/src/freesasa.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/lexer.c -o build/temp.linux-x86_64-3.7/lib/src/lexer.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/log.c -o build/temp.linux-x86_64-3.7/lib/src/log.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/nb.c -o build/temp.linux-x86_64-3.7/lib/src/nb.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/node.c -o build/temp.linux-x86_64-3.7/lib/src/node.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/parser.c -o build/temp.linux-x86_64-3.7/lib/src/parser.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/pdb.c -o build/temp.linux-x86_64-3.7/lib/src/pdb.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/rsa.c -o build/temp.linux-x86_64-3.7/lib/src/rsa.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/sasa_lr.c -o build/temp.linux-x86_64-3.7/lib/src/sasa_lr.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/sasa_sr.c -o build/temp.linux-x86_64-3.7/lib/src/sasa_sr.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/selection.c -o build/temp.linux-x86_64-3.7/lib/src/selection.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/structure.c -o build/temp.linux-x86_64-3.7/lib/src/structure.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c lib/src/util.c -o build/temp.linux-x86_64-3.7/lib/src/util.o -DHAVE_CONFIG_H -std=gnu99
cc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/build/3.7.4/host/include/python3.7m -c freesasa.c -o build/temp.linux-x86_64-3.7/freesasa.o -DHAVE_CONFIG_H -std=gnu99
creating build/lib.linux-x86_64-3.7
gcc -pthread -shared build/temp.linux-x86_64-3.7/lib/src/classifier.o build/temp.linux-x86_64-3.7/lib/src/classifier_protor.o build/temp.linux-x86_64-3.7/lib/src/classifier_oons.o build/temp.linux-x86_64-3.7/lib/src/classifier_naccess.o build/temp.linux-x86_64-3.7/lib/src/coord.o build/temp.linux-x86_64-3.7/lib/src/freesasa.o build/temp.linux-x86_64-3.7/lib/src/lexer.o build/temp.linux-x86_64-3.7/lib/src/log.o build/temp.linux-x86_64-3.7/lib/src/nb.o build/temp.linux-x86_64-3.7/lib/src/node.o build/temp.linux-x86_64-3.7/lib/src/parser.o build/temp.linux-x86_64-3.7/lib/src/pdb.o build/temp.linux-x86_64-3.7/lib/src/rsa.o build/temp.linux-x86_64-3.7/lib/src/sasa_lr.o build/temp.linux-x86_64-3.7/lib/src/sasa_sr.o build/temp.linux-x86_64-3.7/lib/src/selection.o build/temp.linux-x86_64-3.7/lib/src/structure.o build/temp.linux-x86_64-3.7/lib/src/util.o build/temp.linux-x86_64-3.7/freesasa.o -o build/lib.linux-x86_64-3.7/freesasa.cpython-37m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.7/freesasa.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for freesasa.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/freesasa.py to freesasa.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying freesasa.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying freesasa.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying freesasa.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying freesasa.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.freesasa.cpython-37: module references __file__
creating dist
creating 'dist/freesasa-2.0.5.post2-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing freesasa-2.0.5.post2-py3.7-linux-x86_64.egg
creating /home/circleci/repo/cpython/build/3.7.4/host/lib/python3.7/site-packages/freesasa-2.0.5.post2-py3.7-linux-x86_64.egg
Extracting freesasa-2.0.5.post2-py3.7-linux-x86_64.egg to /home/circleci/repo/cpython/build/3.7.4/host/lib/python3.7/site-packages
Adding freesasa 2.0.5.post2 to easy-install.pth file

Installed /home/circleci/repo/cpython/build/3.7.4/host/lib/python3.7/site-packages/freesasa-2.0.5.post2-py3.7-linux-x86_64.egg
Processing dependencies for freesasa==2.0.5.post2
Finished processing dependencies for freesasa==2.0.5.post2
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/classifier.c -o build/temp.linux-x86_64-3.7/lib/src/classifier.bc -DHAVE_CONFIG_H -std=gnu99
lib/src/classifier.c:990:19: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
    for (i = 0; i < sizeof(bb)/sizeof(const char*); ++i) {
                ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/classifier_protor.c -o build/temp.linux-x86_64-3.7/lib/src/classifier_protor.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/classifier_oons.c -o build/temp.linux-x86_64-3.7/lib/src/classifier_oons.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/classifier_naccess.c -o build/temp.linux-x86_64-3.7/lib/src/classifier_naccess.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/coord.c -o build/temp.linux-x86_64-3.7/lib/src/coord.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/freesasa.c -o build/temp.linux-x86_64-3.7/lib/src/freesasa.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/lexer.c -o build/temp.linux-x86_64-3.7/lib/src/lexer.bc -DHAVE_CONFIG_H -std=gnu99
lexer.c:1180:3: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
                YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lexer.c:679:18: note: expanded from macro 'YY_INPUT'
                for ( n = 0; n < max_size && \
                             ~ ^ ~~~~~~~~
lexer.c:1740:17: warning: comparison of integers of different signs: 'yy_size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
        for ( i = 0; i < _yybytes_len; ++i )
                     ~ ^ ~~~~~~~~~~~~
lexer.c:1284:17: warning: unused function 'yyunput' [-Wunused-function]
    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
                ^
lexer.c:1328:16: warning: function 'input' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static int input  (yyscan_t yyscanner)
               ^
4 warnings generated.
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/log.c -o build/temp.linux-x86_64-3.7/lib/src/log.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/nb.c -o build/temp.linux-x86_64-3.7/lib/src/nb.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/node.c -o build/temp.linux-x86_64-3.7/lib/src/node.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/parser.c -o build/temp.linux-x86_64-3.7/lib/src/parser.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/pdb.c -o build/temp.linux-x86_64-3.7/lib/src/pdb.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/rsa.c -o build/temp.linux-x86_64-3.7/lib/src/rsa.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/sasa_lr.c -o build/temp.linux-x86_64-3.7/lib/src/sasa_lr.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/sasa_sr.c -o build/temp.linux-x86_64-3.7/lib/src/sasa_sr.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/selection.c -o build/temp.linux-x86_64-3.7/lib/src/selection.bc -DHAVE_CONFIG_H -std=gnu99
lib/src/selection.c:115:23: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
        for (i = 0; i < strlen(e->value); ++i)
                    ~ ^ ~~~~~~~~~~~~~~~~
1 warning generated.
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/structure.c -o build/temp.linux-x86_64-3.7/lib/src/structure.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c lib/src/util.c -o build/temp.linux-x86_64-3.7/lib/src/util.bc -DHAVE_CONFIG_H -std=gnu99
emcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilib/src -I. -I/home/circleci/repo/cpython/installs/python-3.7.4/include/python3.7 -c freesasa.c -o build/temp.linux-x86_64-3.7/freesasa.bc -DHAVE_CONFIG_H -std=gnu99
emcc -O3 -s BINARYEN_METHOD=native-wasm -Werror -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s SIDE_MODULE=1 -s WASM=1 -s BINARYEN_TRAP_MODE=clamp --memory-init-file 0 -s LINKABLE=1 -s EXPORT_ALL=1 -s ERROR_ON_MISSING_LIBRARIES=0 -pthread -shared build/temp.linux-x86_64-3.7/lib/src/classifier.bc build/temp.linux-x86_64-3.7/lib/src/classifier_protor.bc build/temp.linux-x86_64-3.7/lib/src/classifier_oons.bc build/temp.linux-x86_64-3.7/lib/src/classifier_naccess.bc build/temp.linux-x86_64-3.7/lib/src/coord.bc build/temp.linux-x86_64-3.7/lib/src/freesasa.bc build/temp.linux-x86_64-3.7/lib/src/lexer.bc build/temp.linux-x86_64-3.7/lib/src/log.bc build/temp.linux-x86_64-3.7/lib/src/nb.bc build/temp.linux-x86_64-3.7/lib/src/node.bc build/temp.linux-x86_64-3.7/lib/src/parser.bc build/temp.linux-x86_64-3.7/lib/src/pdb.bc build/temp.linux-x86_64-3.7/lib/src/rsa.bc build/temp.linux-x86_64-3.7/lib/src/sasa_lr.bc build/temp.linux-x86_64-3.7/lib/src/sasa_sr.bc build/temp.linux-x86_64-3.7/lib/src/selection.bc build/temp.linux-x86_64-3.7/lib/src/structure.bc build/temp.linux-x86_64-3.7/lib/src/util.bc build/temp.linux-x86_64-3.7/freesasa.bc -o build/lib.linux-x86_64-3.7/freesasa.cpython-37m-x86_64-linux-gnu.wasm
Define environment variable USE_CYTHON to build from Cython source
running install
running install_lib
creating install
creating install/lib
creating install/lib/python3.7
creating install/lib/python3.7/site-packages
copying build/lib.linux-x86_64-3.7/freesasa.so -> install/lib/python3.7/site-packages
running install_headers
creating install/include
creating install/include/python3.7m
creating install/include/python3.7m/freesasa
copying lib/src/nb.h -> install/include/python3.7m/freesasa
copying lib/src/lexer.h -> install/include/python3.7m/freesasa
copying lib/src/sasa_lr.c -> install/include/python3.7m/freesasa
copying lib/src/freesasa.c -> install/include/python3.7m/freesasa
copying lib/src/nb.c -> install/include/python3.7m/freesasa
copying lib/src/json.c -> install/include/python3.7m/freesasa
copying lib/src/freesasa_internal.h -> install/include/python3.7m/freesasa
copying lib/src/classifier_naccess.c -> install/include/python3.7m/freesasa
copying lib/src/coord.h -> install/include/python3.7m/freesasa
copying lib/src/classifier_oons.c -> install/include/python3.7m/freesasa
copying lib/src/selection.h -> install/include/python3.7m/freesasa
copying lib/src/lexer.c -> install/include/python3.7m/freesasa
copying lib/src/sasa_sr.c -> install/include/python3.7m/freesasa
copying lib/src/main.c -> install/include/python3.7m/freesasa
copying lib/src/pdb.h -> install/include/python3.7m/freesasa
copying lib/src/structure.c -> install/include/python3.7m/freesasa
copying lib/src/classifier.c -> install/include/python3.7m/freesasa
copying lib/src/parser.h -> install/include/python3.7m/freesasa
copying lib/src/selection.c -> install/include/python3.7m/freesasa
copying lib/src/classifier.h -> install/include/python3.7m/freesasa
copying lib/src/coord.c -> install/include/python3.7m/freesasa
copying lib/src/pdb.c -> install/include/python3.7m/freesasa
copying lib/src/util.c -> install/include/python3.7m/freesasa
copying lib/src/classifier_protor.c -> install/include/python3.7m/freesasa
copying lib/src/node.c -> install/include/python3.7m/freesasa
copying lib/src/freesasa.h -> install/include/python3.7m/freesasa
copying lib/src/xml.c -> install/include/python3.7m/freesasa
copying lib/src/parser.c -> install/include/python3.7m/freesasa
copying lib/src/rsa.c -> install/include/python3.7m/freesasa
copying lib/src/log.c -> install/include/python3.7m/freesasa
copying lib/src/example.c -> install/include/python3.7m/freesasa
running install_egg_info
running egg_info
writing freesasa.egg-info/PKG-INFO
writing dependency_links to freesasa.egg-info/dependency_links.txt
writing top-level names to freesasa.egg-info/top_level.txt
reading manifest file 'freesasa.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'freesasa.egg-info/SOURCES.txt'
Copying freesasa.egg-info to install/lib/python3.7/site-packages/freesasa-2.0.5.post2-py3.7.egg-info
running install_scripts
Remember to build the main file with  -s FORCE_FILESYSTEM=1  so that it includes support for loading this file package
converting to ArrayBuffer
compressing package of size 948727
compressed package into 456909
compressed in 40 ms
/home/circleci/repo/pyodide_build/common.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(fd)
patching file sklearn/utils/_joblib.py
Partial import of sklearn during the build process.
/home/circleci/repo/cpython/build/3.7.4/host/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
blas_src_info:
  NOT AVAILABLE
```

**Comment by smkm** [comment]
`packages/micropip/test_micropip.py::test_install_custom_url[chrome] FAILED [ 98%]`

**Pull request merged**
