### PR TITLE
USe github releases for deployment

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by rth** [comment]
Using Github releases could work. The only issue is that it would send a notification (e.g. email) for each new release for all people watching the repo, I think. If that happens for each commit it may become problematic.

AWS S3 or some equivalent might have been simplest but there the issue would be how to associate access to specific Github accounts (and if the service is free for open-source it's probably better).

**Comment by mdboom** [comment]
My plan here is to do this only for tags, so hopefully the spamming will be minimal.  See https://github.com/iodide-project/iodide/pull/1122 for the other part of this.  All of this is to the end of using something other than Github Pages for deployment.  The current plan is to use Heroku, since we're using that for Iodide itself already.

**Comment by rth** [comment]
Aww great! I missed the tag filter - for tags it definitely makes sense.

**Comment by rth** [comment]
Not sure why CI wasn't triggered on the latest commit on master.  Also looking at [ghr docs](https://github.com/tcnksm/ghr), I don't understand what would happen if the current commit is not tagged. i.e. `CIRCLE_TAG` would probably be empty then and we would try to upload files to a non existing release?

**Comment by rth** [comment]
> Deployment should only happen on a tagged commit -- that's the purpose of filters: tags: only: if I understand it correctly.

Absolutely, looks like I forgot about this points, again.

**Pull request merged**
