### PR TITLE
Allow specifying list of packages

### PR DESCRIPTION
**Pull request by filips123**
This allows specifying a list of packages you want to build. It adds `PACKAGES` to ` Makefile.envs` which is then forwarded to `pyodide_build/buildall.py` which then skips packages which are not in that list. By default, it includes all packages but it is possible to change this by the user.

Note that I haven't tested this yet. I'm also not sure how will this handle if package's dependencies are not included in the list, so this should also be tested.

It is related to #579, but I wouldn't close it as I would still like some way to build just packages, without building CPython, Emscripten SDK and Pyodide.

@rth Can you check this?

### CODE REVIEW

**Comment by filips123** [comment]
1. Ok, I will add it.
2. Space-separted but in quotes will probably be OK. I will check and update it.
3. In bash, `*` evaluates to list of all directories in current directory. I don't know if this also works with `Makefile` but I will check it and add a manual check if needed.
4. Ok, I will it add to docs.

**Comment by rth** [comment]
> In bash, * evaluates to list of all directories in current directory. I don't know if this also works with Makefile but I will check it and add a manual check if needed.

Right. I'm never fully sure what happens in Makefiles,  but if you add the parser argument you will see if CI passes. Currently if fails with,
```
pyodide: error: unrecognized arguments: --packages=*
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/circleci/repo/packages'
Makefile:249: recipe for target 'build/packages.json' failed
make: *** [build/packages.json] Error 2
```

**Comment by filips123** [comment]
I now quoted variable and arguments, added check for `*` and added argument to the parser. I also switched to the comma-separated list.

I will create docs when current test passes.

**Comment by mdboom** [comment]
> I will create docs when current test passes. How should that docs look like?

Just something in the build instructions describing how to limit the packages that get built.

**Comment by filips123** [comment]
Sorry for delay. I now added documentation? Is it correct?

**Comment by mdboom** [comment]
This looks good.

Would you mind rebasing this on upstream master?  (The build is broken because the version of emscripten we relied on is no longer available by the name we specify, but this has been fixed in pyodide since you made this PR).

**Comment by rth** [comment]
In the end this got implemented independently with more or less the same functionality in https://github.com/iodide-project/pyodide/pull/645. I'm sorry @filips123 I completely forgot about this PR even though I have commented here not long ago. Closing as resolved.

**Pull request closed without merging**
