### PR TITLE
Add zarr and numcodecs

### PR DESCRIPTION
**Pull request by oeway**
This PR fixes https://github.com/iodide-project/pyodide/issues/924, add `zarr` and `numcodecs`.

### CODE REVIEW

**Comment by oeway** [comment]
Started to get this error after importing `numcodecs`, although it seems to be working:
```
TypeError: Cannot read property 'apply' of undefined
    at obj.<computed> (http://127.0.0.1:46921/pyodide.asm.js:8:10077)
    at _blosc_init (<anonymous>:wasm-function[293]:0x30c89)
    at ___pyx_pw_9numcodecs_5blosc_1init (<anonymous>:wasm-function[240]:0x19041)
    at <anonymous>:wasm-function[990]:0x12fe46
    at _cfunction_vectorcall_NOARGS (http://127.0.0.1:46921/pyodide.asm.wasm:wasm-function[1718]:0x183d31)
    at http://127.0.0.1:46921/pyodide.asm.wasm:wasm-function[18895]:0x9a554d
    at _call_function (http://127.0.0.1:46921/pyodide.asm.wasm:wasm-function[2849]:0x250aca)
    at __PyEval_EvalFrameDefault (http://127.0.0.1:46921/pyodide.asm.wasm:wasm-function[2842]:0x24bf0e)
    at http://127.0.0.1:46921/pyodide.asm.wasm:wasm-function[19369]:0x9a7193
    at __PyEval_EvalCodeWithName (http://127.0.0.1:46921/pyodide.asm.wasm:wasm-function[2837]:0x244dce)
    at _PyEval_EvalCode (http://127.0.0.1:46921/pyodide.asm.wasm:wasm-function[2836]:0x243f7a)
```

Any idea on how to debug this type of issue? something related to `_blosc_init`?

**Comment by oeway** [comment]
Checked the definition of `blosc_init`, it tries to initialising pthread. Have we enabled pthread support? should we disable that? @rth 
```c
void blosc_init(void)
{
  /* Return if we are already initialized */
  if (g_initlib) return;

  global_comp_mutex = (pthread_mutex_t*)my_malloc(sizeof(pthread_mutex_t));
  pthread_mutex_init(global_comp_mutex, NULL);

  g_global_context = (struct blosc_context*)my_malloc(sizeof(struct blosc_context));
  g_global_context->threads_started = 0;

  #if !defined(_WIN32)
  /* atfork handlers are only be registered once, though multiple re-inits may
   * occur via blosc_destroy/blosc_init.  */
  if (!g_atfork_registered) {
    g_atfork_registered = 1;
    pthread_atfork(NULL, NULL, &blosc_atfork_child);
  }
  #endif

  g_initlib = 1;
}
```

**Comment by rth** [comment]
> Have we enabled pthread support? 

Not yet #237 , it would indeed be necessary to disable it.

**Comment by oeway** [comment]
@rth Thanks, disabled pthread and now passed my tests locally. Let's see how it goes with the CI.

**Comment by rth** [comment]
Great! Please add zarr to the list of new packages in docs/changelog.md and add comments as a first few line of patches with a description (#857)

**Comment by oeway** [comment]
@rth This PR is ready, all the tests pass except the benchmark which is not related.

**Comment by rth** [comment]
Thanks @oeway !

**Pull request merged**
