### PR TITLE
Partially address #338: Provide simple method for interactive testing

### PR DESCRIPTION
**Pull request by mdboom**
This adds a basic repl-like console webpage that can be used for
testing of the local pyodide install.

It removes the broken examples based on standalone iodide.

Cc: @msabramo

### CODE REVIEW

**Comment by madhur-tandon** [comment]
@mdboom Does this also support plotting (and seeing the graphs) through ``matplotlib``? I guess no, right? I tried plotting (while simultaneously opening ``matplotlib-sideload.html``) but I couldn't get it to work [maybe it's not the right way to do so]. Lastly, is there a way I could track my cursor when I go back and forth between the already typed text?

**Comment by mdboom** [comment]
It doesn't support matplotlib.  I spent some time last week working on that, but the `jquery-terminal` library used here doesn't seem to support adding arbitrary DOM elements (that don't get otherwise replaced at a later time).  Unless there's some creative solution I'm missing, I think we'd have to look at another console library to make that work.

I also have seen the bug moving the cursor backward.  That's probably something we should report upstream to `jquery-terminal`.

I'm sort of leaning on merging this, even thought it's not perfect, to have some handy method for local testing, and we can iterate on these issues later.  I don't want to spend a *ton* of time on this that could be better spent making the *real* nice interface in Iodide.

**Comment by rth** [comment]
Thanks @mdboom, I think having a simple standalone REPL is indeed quite useful. 

So far I got distracted by how to test this feature using the generated CircleCI artifacts, without downloading them one by one or building pyodide locally.  Will try to review in more detail today or tomorrow.

**Comment by madhur-tandon** [comment]
Writing anything after a ``print`` statement does not clear the previous buffer. Stuff that was passed on earlier to ``print`` (both strings and variables) seem to repeat again when any other command is subsequently used. Although this shouldn't affect our testing ability, it could get a bit irritating in the long term.

Screenshot 2019-03-20 at 1 37 14 AM

**Comment by mdboom** [comment]
Thanks for the report, @madhur-tandon.  That should be easy to fix.

**Comment by msabramo** [comment]
Love this!

One small bug - this is similar to what @madhur-tandon reported perhaps, except that I'm seeing repeated output of the previous command when I enter a multi-line command:

Screen Shot 2019-03-20 at 10 54 28 PM

But this is very cool and in my mind helps address the issue I raised in #338.

👍

**Comment by msabramo** [comment]
@mdboom: I propose this fix for the issue I mentioned in https://github.com/iodide-project/pyodide/pull/343#issuecomment-475120834:

```diff
diff --git a/build/console.html.2019-03-21-082631 b/build/console.html
index 83e89ce..00747c5 100644
--- a/build/console.html.2019-03-21-082631
+++ b/build/console.html
@@ -43,7 +43,11 @@
           if (stderr) {
             term.echo(`[[;red;]${stderr}]`)
           } else {
-            var stdout = pyodide.runPython("sys.stdout.getvalue()")
+            var stdout = pyodide.runPython(`
+              __output__ = sys.stdout.getvalue()
+              sys.stdout = io.StringIO()
+              __output__
+            `)
             if (stdout) {
               term.echo(stdout.trim())
             }
```

Screenshot:

Screen Shot 2019-03-21 at 8 25 30 AM

**Comment by mdboom** [comment]
@msabramo: Thanks.  I was simultaneously looking at this and found a slightly simpler solution.  I've tested it with your example above, but kick the tires one more time and let me know.

**Comment by msabramo** [comment]
@mdboom: Oh yeah, your way is simpler and works too. 👍

**Comment by msabramo** [comment]
@mdboom: I have one small tweak to make the Python code look nicer:

https://github.com/mdboom/pyodide/pull/2

**Comment by houshuang** [comment]
Is there any documentation somewhere on how graphics get plotted etc? I'd like to build on this and explore some components where users can enter code, and run, based on React... I keep seeing references to plotting from matplotlib, HTML files etc, but no API... if I was just calling the pyiodide API programmatically, how would I return/plot the output of matplotlib?

**Comment by mdboom** [comment]
To use matplotlib plotting outside of iodide at the moment, you'll need to subclass `matplotlib.backends.wasm_backend.py::FigureCanvasWasm` and provide your own implementation of create_root_element that knows how to insert a DOM element into your system.

https://github.com/iodide-project/pyodide/blob/master/packages/matplotlib/src/wasm_backend.py#L104

It's difficult to provide a better API than this since how that works depends a lot of the JS framework being used.

**Pull request merged**
