### PR TITLE
Adds Sphinx documentation build

### LINKED ISSUE #420: Add documentation to ReadTheDocs
Hi @mdboom 🐍 

To increase visibility and discovery of the project, perhaps creating a sphinx site on RTD using the Markdown files in the repo would be helpful.

If you have interest, I could do a quick doc PR this week.

### PR DESCRIPTION
**Pull request by willingc**
Closes #420

- Adds Sphinx build of existing Markdown files
- Corrects a few bad links that were causing warnings on Sphinx build
- Adds a RTD yaml file to base of repo (I suspect someone who has permissions for pyodide on RTD will need to do the initial doc creation/build - Happy to doublecheck it if you add me as a docs maintainer on RTD).
- Adds a box on landing page referring to Iodide alpha landing page (looks nice) and a link to the Iodide docs

[Rendered - test build on RTD](https://test-pyodide.readthedocs.io/en/sphinx/)

### CODE REVIEW

**Comment by mdboom** [comment]
This looks great.  I assume that post merging this also requires some setup on readthedocs?

**Comment by rth** [comment]
Yes, enabling this repo at readthedocs would be needed, so that each commit on master triggers a build.

**Comment by willingc** [comment]
Yes, a RTD account needs to be created with maintainers added. The webhook for build on commit should automatically be activated. Though it makes sense to double-check. Once this lands, I can add info on building docs locally.

**Comment by mdboom** [comment]
This is merged and deployed to `pyodide.readthedocs.io`.  Thanks again, @willingc.

**Pull request merged**
