### PR TITLE
Use strict in emjs

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Comment by hoodmane** [comment]
With the help of `"use strict";` I just fixed an interesting peculiarity of the code. The `destroy` function used to globally write to `ptrobj`. Here's the behavior:
```javascript
    destroy : function() {
      ptrobj = Module.PyProxy.getPtr(this);
      // this ^^ is a global assignment
      // because ptrobj is undeclared and sloppy mode semantics.
      __pyproxy_destroy(ptrobj);
      this['$$']['ptr'] = null;
    },
```
Then 
```C
void
_pyproxy_destroy(PyObject* ptrobj)
{
  Py_DECREF(ptrobj);
  // EM_ASM does not see C variables. the ptrobj 
  // below is actually reading the global value of ptrobj.
  // Unfortunately, we also just leaked the value of ptrobj to the global scope,
  // so this always behaves as expected despite being completely wrong.
  EM_ASM(delete Module.PyProxies[ptrobj];);
}
```

**Comment by dalcde** [comment]
At the end, is the "move stuff around in pyproxy" change necessary for tests to pass?

**Comment by hoodmane** [comment]
No, though that change is an improvement. I suppose it should be split into a separate PR.

**Comment by hoodmane** [comment]
Though the diff here isn't super big and splitting it off will take more effort.

**Comment by hoodmane** [comment]
I was just hunting for the change on line 155 which was hard to spot.

**Comment by dalcde** [comment]
I think it is better to keep to one change per PR. Having a change totally unrelated to the PR topic can be very confusing for future people

**Pull request merged**
