### PR TITLE
Run tests in parallel

### PR DESCRIPTION
**Pull request by dalcde**
See #76

### CODE REVIEW

**Comment by dalcde** [comment]
It appears that our main bottleneck with parallel tests is the runner running out of memory (see e.g. https://stackoverflow.com/q/49734915). I'll lower the number of cores to 2, which should still help quite a bit.

**Comment by dalcde** [comment]
Of course, feel free to incorporate the changes into #828. This PR is mostly to figure out how the runner fares with multiple tests running.

**Comment by dalcde** [comment]
Unsurprisingly, this halves the testing time.

**Comment by rth** [comment]
Thanks for investigating! I think earlier we couldn't use it as it failed even with 2 processes https://github.com/iodide-project/pyodide/issues/76#issuecomment-405999871 but memory usage have been improved since.

Note that the CI images show 32 CPU but only 2 can be used (limited when running Docker image I imagine), so running the test suite with 2 processes is already quite good.

**Pull request merged**
