### PR TITLE
Vendor file_packager.py

### PR DESCRIPTION
**Pull request by mdboom**
As discussed [here](https://github.com/iodide-project/pyodide/pull/152#issuecomment-420612348), this moves file_packager.py into our own repository so we can iterate on changes to it faster.

(Though we should still have the goal of upstreaming changes to emscripten in the long run).

### CODE REVIEW

**Comment by rth** [comment]
Also maybe it could be worth amending the commit to indicate which version of emscripten this corresponds to? or put it in a comment ?

**Comment by mdboom** [comment]
I've fixed this so it's an exact copy (patched only to work from a new location), and added a comment that it's forked from emscripten 1.38.10.

**Comment by rth** [comment]
Actually, `file_packager.py` [is also called in `emcc.py`](https://github.com/kripken/emscripten/blob/e1f53a27fe561a2fc43c4a256d849620516e23de/emcc.py#L1812).

Doesn't that mean that we are currently mixing two `file_packager.py` versions: one vendored and one not? Should we also replace the `file_packager.py` in emsdk with our version?

**Comment by mdboom** [comment]
I think it's only called from `emcc.py` though if you are having it handle the file packaging, which we aren't.  I suppose there is an issue if a user were trying to use emcc directly to build a pyodide package, but that's going to be tricky and the recommended way would be to go through pyodide_build anyway.

Despite all that, I'm not opposed to copying it over as part of the `emsdk` Makefile just to be certain.

**Comment by rth** [comment]
You are right, it's only used `if len(options.preload_files) or len(options.embed_files)`, so keeping the current way of things should be fine. I agree that using `emcc.py` from emsdk included in pyodide without `pyodide_build` is not something we would probably want to support.

**Pull request merged**
