### PR TITLE
Rename deepCopyToJavascript -> toJs & rm shallowCopyToJavascript

### PR DESCRIPTION
**Pull request by hoodmane**
As discussed in #1192. Closes #1208.

### CODE REVIEW

**Review by phorward — APPROVED** [review]
Hello @hoodmane,
Thanks for the renaming, I'm fine with this.
Is it maybe useful and possible to provide tests with deep-parameter setting > 1 ?

**Comment by hoodmane** [comment]
Thanks for the review @phorward!

> Is it maybe useful and possible to provide tests with deep-parameter setting > 1 ?

Yes, both useful and possible. These tests already exist in disguise, in the form of `test_python2js_with_depth` in `test_typeconversions`. I think I will convert that one to use `toJs` and remove the private test entrypoint in `python2js` now that there is a public way to access this API.

**Comment by hoodmane** [comment]
I am going to need to update `test_python2js_with_depth` in #1234 anyways, so I think this PR should be merged as-is and I can do the cleanup in #1234.

**Comment by rth** [comment]
Thanks! Sounds good to me as well.

**Pull request merged**
