### PR TITLE
Don't compile host python

### PR DESCRIPTION
**Pull request by dalcde**
This requires the build system to use python3.8, which can be acheived by tools like pyenv if needs be.

### CODE REVIEW

**Comment by rth** [comment]
FYI, you can use pre-commit to catch most of those linting issues.
```
pip install pre-commit
pre-commit install
```

**Comment by dalcde** [comment]
The benchmark failure is because the packages we build are installed into a temporary directory, which does not persist between builds. This would be a problem for real-life users too.

**Comment by rth** [comment]
Good to see that it's working and thanks for looking into this @dalcde !

I see that with ccache it doesn't reduce the build times too much in CI, but the simplification of the CPython build setup is very welcome. 

My only concern is to make sure this indeed works outside of docker when the system python is not 3.8. In particular, I'd like to try it inside a conda virtualenv as that would solve the question of how to install the correct version of python. And if it does we should update the documentation.

**Review by rth — APPROVED** [review]
OK, I checked this does work in a conda env, after applying the https://github.com/iodide-project/pyodide/pull/835  (unrelated) fix with,

```
sudo apt install libtinfo5 build-essential 
conda create -c conda-forge -n pyodide-env pyyaml nodejs python=3.8.2
conda activate pyodide-env
npm install -g uglify-js
make
```

LGTM, great work! I think we can merge and update the "building from sources" documentation in a follow up PR as it could an update in general.

**Pull request merged**
