### PR TITLE
Make a copy of `console.html` at `builld/index.html`

### PR DESCRIPTION
**Pull request by hoodmane**
The standard for websites is to make `index.html` be the main file. Since our main file is `console.html`, I propose we should make a copy at `index.html`.

I also added a title and some meta tags.

### CODE REVIEW

**Comment by rth** [comment]
I was thinking that in the future we should put the list of packages as the index.html. But that would probably require doing #791 first (I have a partial solution, need to make a PR).

**Comment by hoodmane** [comment]
I think it's good to put something there, we can always change it later. I can just fetch packages.json and iterate over it in js...

**Comment by hoodmane** [comment]
I think we should start with a link to the console and then to the docs. Then the list of packages would be good. If possible it would be nice to insert links to the package docs / pypi.

**Comment by dalcde** [comment]
Do you want to close this PR and turn it into an issue?

**Comment by hoodmane** [comment]
Sounds good to me.

**Pull request closed without merging**
