### PR TITLE
BLD Fix overwriting package optflags via clfags etc in meta.yaml

### PR DESCRIPTION
**Pull request by rth**
Previously if a Python package was compiled with some optflags, for instance,
```
  gcc -O3 test.c -o test.o
```
and some cflags were provided in `meta.yaml` with a different optimization level such as `cflags='-Oz'`, then they would be injected by `handle_command` at the beginning of the command as,
```
  emcc -Oz -O3 test.c -o test.o
```
Then because when multiple optimization options are passed, clang [would take the last one](https://stackoverflow.com/a/61831017/1791279) thus ignoring the optimization option from cflags.

This fixes this issue by only taking the optflag from cflags/cxxflags/ldflags when they are conflicting with earlier optflags present in the initial command.

A simpler way of solving this could have been to append clfags, etc instead of prepending them. However I feel this would result in harder to read logs with potentially conflicting information and it doesn't take that much work to fix it, as done in this PR

### CODE REVIEW

**Comment by rth** [comment]
@hoodmane Could you have a look at this PR?

**Comment by hoodmane** [comment]
Presumably the line `gcc -O3 test.c -o test.o` comes from the `Makefile` and the `-Oz` added in `meta.yaml` might be for debugging purposes? It sounds useful to have the `-Oz` flag actually take effect, though if just for debugging one could also just modify the `Makefile`. The logic you described sounds reasonable and like it's an improvement. The implementation looks good.

My understanding of the build system is still extremely limited though, so my opinions about this should probably be taken with a grain of salt.

**Comment by rth** [comment]
Thanks for the review!

> Presumably the line gcc -O3 test.c -o test.o comes from the Makefile and the -Oz added in meta.yaml might be for debugging purposes?

Not exactly. The issue is that you compile an arbitrary Python C extension on x86_64, in my experience, it will be compiled with `-O3`. I'm not exactly sure where it's coming from, we specify [O2 in the Makefile](https://github.com/iodide-project/pyodide/blob/a1241301dcd28d01c855de0d109f8a55ee7b4ea0/Makefile#L15), maybe something to do with `python3-config --cflags` . 

And because we take those exact commands and change the compiler to build with emcc, the final modules are going to be built with `-O3` even if we didn't ask for it. That's might not be ideal because `-O3` results in noticeably [larger output sizes](https://discuss.python.org/t/why-does-cpython-use-o3/1915/13) with [relatively small performance improvement](https://discuss.python.org/t/why-does-cpython-use-o3/1915/9). So in our case, it might well be that `Os` (i.e. `O2` + size optimization) or `Oz` ( `O2` + more size optimizations) might be preferable. Of course we could set those globally for all packages, but it's also useful to be able to set them per package (including for debugging).

**Comment by hoodmane** [comment]
Interesting! From the gcc docs:

> -O2 is the recommended level of optimization unless the system has special needs.
> ...
> Compiling with -O3 is not a guaranteed way to improve performance, and in fact, in many cases, can slow down a system due to larger binaries and increased memory usage. -O3 is also known to break several packages. Using -O3 is not recommended.

**Comment by hoodmane** [comment]
I guess the benchmarks in the thread you linked show a ~5% speedup (eyeballing an average) for `-O3` over `-O2` and the binary is 20% larger with `-O3` than with `-O2`.

**Pull request merged**
