### PR TITLE
Combine pyproxy_new and pyproxy_use into pyproxy_new

### PR DESCRIPTION
**Pull request by hoodmane**
The difference between pyproxy_new and py_proxy_use is a pyproxy implementation detail. Combined them into get_pyproxy.

### CODE REVIEW

**Comment by hoodmane** [comment]
No effort yet to address #1049.

**Comment by rth** [comment]
I'm not sure this factorization is worth it. You do remove `pyproxy_new` and `pyproxy_use` from the header, but then add a new function, which also doesn't follow the implied `pyproxy_<action>` naming convention. Also `pyproxy_get` already exist and can be confused with `get_pyproxy`. 

Maybe meging `pyproxy_new` and `pyproxy_use` into a single function (possibly still `pyproxy_use`) would be better? They have 7 LoC among them.

Or keeping the code as it is is also fine IMO.

**Comment by hoodmane** [comment]
> I'm not sure this factorization is worth it

I think these two functions need to be merged. Consider the following code from the current `py2js`:
```C
    ret = pyproxy_use(x);
    return get_pyproxy(x);
    if (ret != NULL) {
      return ret;
    }

    // Reference counter is increased only once when a PyProxy is created.
    Py_INCREF(x);
    return pyproxy_new(x);
```
This is what you are supposed to do every time you need a `PyProxy`. This pollutes the call site with an implementation detail from `pyproxy`.

**Comment by hoodmane** [comment]
> Maybe merging `pyproxy_new` and `pyproxy_use` into a single function (possibly still `pyproxy_use`) would be better? They have 7 LoC among them.

That sounds like the right choice to me.

**Comment by hoodmane** [comment]
We currently get a `JsProxy` by calling `JsProxy_cnew`. Why don't we call the function `pyproxy_new`? Also if it's going to be `JsProxy` shouldn't it be `PyProxy`?

**Comment by rth** [comment]
>  Also if it's going to be JsProxy shouldn't it be PyProxy

`pyproxy_new` sounds good. If you change it to PyProxy_new you would need to also change all other functions for consistency. Maybe let's avoid it for now, to much code churn also make using git blame hader..

**Comment by hoodmane** [comment]
If I get around to doing a `pyproxy` refactor I can rename it then.

**Comment by hoodmane** [comment]
@dalcde @rth Still a lot of improvement to be had in conftest:
See [this test failure](https://app.circleci.com/pipelines/github/iodide-project/pyodide/1165/workflows/86ec6230-b4e8-4bc4-b1a5-0b141a22f71e/jobs/13928): no information is conveyed about the nature of the error. If I go to `console.html` locally I see the following perfectly diagnostic message in the browser console.
```javascript
pyodide.asm.js:8 exception thrown: ReferenceError: x is not defined,ReferenceError: x is not defined
    at _pyproxy_new (http://localhost:8002/pyodide.asm.js:8:188778)
    at __python2js (http://localhost:8002/pyodide.asm.wasm:wasm-function[387]:0x108a51)
    at _python2js (http://localhost:8002/pyodide.asm.wasm:wasm-function[389]:0x108e72)
    at _runpython_init (http://localhost:8002/pyodide.asm.wasm:wasm-function[410]:0x109822)
    at _main (http://localhost:8002/pyodide.asm.wasm:wasm-function[321]:0x10690a)
    at Object.Module._main (http://localhost:8002/pyodide.asm.js:8:2822531)
    at callMain (http://localhost:8002/pyodide.asm.js:8:3472842)
    at doRun (http://localhost:8002/pyodide.asm.js:8:3473421)
    at run (http://localhost:8002/pyodide.asm.js:8:3473593)
    at runCaller (http://localhost:8002/pyodide.asm.js:8:3472493)
```

**Pull request merged**
