### PR TITLE
Use latest version of python packages

### PR DESCRIPTION
**Pull request by sergio97**

### CODE REVIEW

**Comment by mdboom** [comment]
Curious how you decided which packages to upgrade here (since it isn't all)?  Just the "easy" ones without compilation? -- That's a completely valid approach to go after the low-hanging fruit, of course -- more just asking what the roadblocks were with some of the packages not updated here.

**Comment by sergio97** [comment]
Screenshot from 2019-11-19 14-51-12

**Comment by sergio97** [comment]
of the 5 that had patches:
- pyparsing patches didn't apply - I decided not to update it.
- pytz patches still applied
- joblib patches were updated
- attrs patches were updated
- python-dateutil patches didn't apply - I decided not to update it.

**Comment by mdboom** [comment]
Looks like joblib has grown a dependency on `pkg_resources`:

```
E       selenium.common.exceptions.JavascriptException: Message: Error: Traceback (most recent call last):
E         File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
E           exec(compile(mod, '<exec>', mode='exec'), ns, ns)
E         File "<exec>", line 1, in <module>
E         File "/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
E           from .memory import Memory, MemorizedResult, register_store_backend
E         File "/lib/python3.7/site-packages/joblib/memory.py", line 32, in <module>
E           from ._store_backends import StoreBackendBase, FileSystemStoreBackend
E         File "/lib/python3.7/site-packages/joblib/_store_backends.py", line 16, in <module>
E           from .backports import concurrency_safe_rename
E         File "/lib/python3.7/site-packages/joblib/backports.py", line 8, in <module>
E           from pkg_resources import parse_version
E       ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by sergio97** [comment]
Reverted joblib and udpated the other 2 packages. Hopefully the builds pass now...

**Comment by sergio97** [comment]
Packages
========
**Pygments** 2.3.1 -> 2.4.2
**atomicwrites** 1.1.5 -> 1.3.0
**attrs** 18.1.0 -> 19.3.0
**biopython** 1.73 -> 1.75
**decorator** 4.3.0 -> 4.4.1
**distlib** 0.2.8 -> 0.3.0
**docutils** 0.14 -> 0.15.2
**kiwisolver** 1.0.1 -> 1.1.0
**more-itertools** 4.3.0 -> 7.2.0
**nltk** 3.4 -> 3.4.5
**py** 1.5.4 -> 1.8.0
**pyparsing** 2.2.0 -> 2.4.5
**python-dateutil** 2.7.2 -> 2.8.1
**pytz** 2018.4 -> 2019.3
**regex** 2019.08.19 -> 2019.11.1
**soupsieve** 1.8 -> 1.9.5

**Comment by wlach** [comment]
Thanks @sergio97, everything looks good except for the chrome tests (which are known to be flakey). I will go ahead and merge.

**Pull request merged**
