### PR TITLE
Add Pandas to the build

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by bcolloran** [comment]
:fireworks: rad :+1:

**Comment by hamilton** [comment]
@mdboom is there any action needed on this from our end before merging?

**Comment by mdboom** [comment]
No, I was just hoping to solve some other performance issues before merging this, since this is a major increase in file and code size.

**Comment by hamilton** [comment]
🎉🎉🎉🎉🎉

Is this running smoothly enough to use?

**Comment by mdboom** [comment]
Just working through a few final issues -- it's failing on Travis but passing on my local machine.

**Pull request merged**
