### PR TITLE
PyProxy methods for iterators / iterables / generators

### PR DESCRIPTION
**Pull request by hoodmane**
A PyProxy of an iterable Python object is now an iterable Javascript object, 
a PyProxy of a Python iterator is now an Javascript iterator,
a PyProxy of a Python generator is now a Javascript generator.

### CODE REVIEW

**Comment by rth** [comment]
Thanks @hoodmane ! This sounds great. Sorry not much review bandwidth at the moment, but all your suggested improvement are very much appreciated :) I'll try to have a look later in the week or next week. At the moment mostly focusing on https://github.com/iodide-project/pyodide/pull/1102 as it's blocking a number long standing of issues.

**Review by phorward — APPROVED** [review]
Hello @hoodmane,
great, this is just another fine pull request, and as @rth said your suggestions are very much appreciated here!
The hiwire.pop_value() replacement is also another good thing coming in with this.
I hope to contribute some more reviewing bandwidth during the next days.
On my first view all looks fine on this, maybe Roman has a comment therefore I first wait at the moment.

**Comment by hoodmane** [comment]
Thanks for the reviews. I really appreciate all the hard work you guys put into maintaining this project. I have faith you'll get to reviewing my PRs eventually =)

**Review by rth — APPROVED** [review]
This is nice! Please add a changelog entry.

Thanks @hoodmane  and @phorward !

**Pull request merged**
